### ISSUE TITLE
Inventory Management with Bundled products

### ISSUE THREAD

**Issue by rzpatel** [smartstore/SmartStoreNET#1052]
When a bundled product type is created, it defaults to the default inventory level (10000). Option to update inventory management is not availabel (tab is hidden). Furthermore if Bundle item individually in the shopping cart is selected, inventory management still manages from the default inventory count.

**Comment by mgesing** [comment]
> Option to update inventory management is not availabel (tab is hidden)
Yes, per definition if "Bundle item individually in the shopping cart" is activated, otherwise not.

**Comment by mgesing** [comment]
Not reproducible. Observed expected behavior: bundle inventory level remains on 10.000 and the level of the bundle items are adjusted.

**Comment by rzpatel** [comment]
Hi,
I do see that the level of the bundled items do get adjusted. The issue I am facing is that a buyer is able to add the bundle to the cart even if the amount of bundled items he add is more than the individual items in the bundle.

For eg

There is a product with an inventory level of 10.
You create a bundled product which has a multipack of this product [eg 2]
The buyer is able to now add 10 bundles to the cart which would be 20 of the individual products whereas there are only 10 available. Once you check out the individual inventory would go into negative.
My assumption is that the way it should work is that at the time of adding the bundle to the cart it should query the individual products in the cart and in the inventory, or should the behavior be as it is currently behaving. [V3.1.5] 
Thanks

**Comment by mgesing** [comment]
You can achieve this with the option **Bundle item individually in the shopping cart**:

> Quantity and price of bundle items appear in the shopping cart. Inventory management based on the bundle items, rather than of the bundle.
