### ISSUE TITLE
Product Import - UI not displaying updates when only product images are changed

### ISSUE THREAD

**Issue by CompleteCoders** [smartstore/SmartStoreNET#1323]
Steps to reproduce:

1. Import a product
2. Change import to add a new image, don't change anything on the product
3. Import product again

Result: 
Total rows: 2 · Skipped: 0
New records: 0 · Updated: 0

Expected:
Total rows: 2 · Skipped: 0
New records: 0 · Updated: 2

**Comment by mgesing** [comment]
Requires too much code and service interface changes to accurately determine the modified number of records. Best solution is to leave it as it is.
