### ISSUE TITLE
System.Data.SqlClient.SqlException: 'Invalid column name 'CreatedOn'.'

### ISSUE THREAD

**Issue by cuongpv88** [smartstore/SmartStoreNET#1467]
System.Data.SqlClient.SqlException: 'Invalid column name 'CreatedOn'.'

**Comment by ericbrunner** [comment]
I still face that issue on Branch **4.0.1** while opening the Google Mercent Center Plugin configuration page.
![image](https://user-images.githubusercontent.com/6480047/97587083-492b6b00-19fb-11eb-8fb6-41e9db9eb177.png)

**Comment by Michael-Herzog** [comment]
Hi Eric,
this error will only be thrown in dev environment every time a migration is about to be executed. The second time you open the configuration page should throw no errors as the migration is applied now.
Regards,
Michael

**Comment by ericbrunner** [comment]
In the meanwhile I found that comment useful https://github.com/smartstore/SmartStoreNET/issues/1259#issuecomment-330598071 thanks anyway.

**Comment by Michael-Herzog** [comment]
Yes, this comment is better than mine, because it is much more detailed.
