### ISSUE TITLE
Does tax by region provide a wrong tax rate when delivering to a tax-exempt country?

### ISSUE THREAD

**Issue by mgesing** [smartstore/SmartStoreNET#1500]
Example: 
Product: price 100,-. VAT 19%.
Shipping country: Switzerland. Not subject to VAT. VAT 7.7% (tax by region).
Calculated price: 92.85 (7.7 applied)
Expected price: 84.03 (19.0 applied)

**Comment by muratcakir** [comment]
Yes, it has to be 84.03 (19.0 applied > Gross - merchant country VAT).
