### ISSUE TITLE
smartcore error

### ISSUE THREAD

**Issue by FloteFuertes** [smartstore/SmartStoreNET#1523]
I am getting an error in the smartcore project after I forked the 3.x . Please advise thanks @muratcakir

**Comment by FloteFuertes** [comment]
![image](https://user-images.githubusercontent.com/21190507/46595386-b31e0280-cb0a-11e8-8049-b14547c95040.png)

**Comment by mgesing** [comment]
Are you using [Visual Studio 2017](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/)?

**Comment by mgesing** [comment]
Then please update to VS 2017. The errors are probably caused by unsupported C# 7.0 features.
