### ISSUE TITLE
category: out of stock  show end list Product

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1567]

**Comment by Michael-Herzog** [comment]
Please explain this in a little more detail. I couldn't understand what is meant by this issue.

**Comment by pineportal** [comment]
There are different methods for categories to be sorted, for example you can sort the categories by alphabet, price or the oldest and newest ones. If you have some products that are unavailable you should sort them to be shown by the beginning or ending of the list. This help customers to search and find what they want simply. This option is now available in category settings and if you want you can activate it.

**Comment by pineportal** [comment]
LinqCatalogSearchService => GetProductQuery

![Screenshot_3](https://user-images.githubusercontent.com/31403448/58985147-f17dd580-87ef-11e9-8081-c69ea941dbcd.jpg)

**Comment by mgesing** [comment]
The benefit is too low or non-existent. The list is already sorted according to the user selection.
In most cases, you wouldn't see the difference. Filter by availability is sufficient here.
