### ISSUE TITLE
Homepage image slider source

### ISSUE THREAD

**Issue by MarshalOfficial** [smartstore/SmartStoreNET#1604]
Hi,
I have installed project and clear some of default data of category and products to define my own data, but i dont know why homepage image slider disappeared and i dont know where is source of this image slider? is it from product category? or product images? and where is that adjustment option?
thanks,

**Comment by MarshalOfficial** [comment]
![sharanslider](https://user-images.githubusercontent.com/8558078/55276960-4e549f80-5318-11e9-86f9-a9ebc65d0b18.png)
![demo](https://user-images.githubusercontent.com/8558078/55276963-5280bd00-5318-11e9-85c7-e8a9d3e24373.png)

**Comment by MarshalOfficial** [comment]
In Documentation website there is a tutorial for arranging content slider
http://docs.smartstore.com/display/SMNET30/Arranging+the+Content+Slider
but in CMS -> there is no content slider option to chosse in admin page.
latest version is forked from github

**Comment by pineportal** [comment]
Content Slider is plugin in ver 3.+
