### ISSUE TITLE
add minor fix css for Breadcrumb

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1606]
for update https://github.com/smartstoreag/SmartStoreNET/commit/d0df1dd8249a8286b1a7f49dd08a10da6e44810a
```
 .breadcrumb-item.active {
     padding: 0 10px;
 }
```

**Comment by Michael-Herzog** [comment]
Looks good the way it is. Can you add a screenshoot to show me the problem?

**Comment by pineportal** [comment]
in RTL
![Screenshot_5](https://user-images.githubusercontent.com/31403448/55551686-a44a8e00-56f0-11e9-828f-56d37c493b49.jpg)

**Comment by Michael-Herzog** [comment]
In RTL it's no problem either with the current code.

**Comment by pineportal** [comment]
i m check ver 3.1.5
