### ISSUE TITLE
EditorTemplates Download cant use plugin

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1614]
UploadUrl dont set area="admin"

![Screenshot_6](https://user-images.githubusercontent.com/31403448/56316504-ac361380-616f-11e9-9e4a-c449c88cd210.jpg)

and add fileTypes in ViewData

![Screenshot_7](https://user-images.githubusercontent.com/31403448/56316566-d091f000-616f-11e9-90fc-354656491626.jpg)

**Comment by pineportal** [comment]
i cant use this in my plugin
![56316504-ac361380-616f-11e9-9e4a-c449c88cd210](https://user-images.githubusercontent.com/31403448/56638641-e75ea800-6683-11e9-8e57-5c9e1f7677cb.jpg)

**Comment by muratcakir** [comment]
Why? `area = "Admin"` is required here, otherwise the route will not be matched.

**Comment by pineportal** [comment]
when use Download  in plugin . for example
`@Html.EditorFor(model => model.DownloadId, "Download")`
can not find route for upload file. 
i want use ~/admin/download/AsyncUpload.
but Currently use ~/MyPkugin/download/AsyncUpload.

I've already implemented the following to fix it
![Screenshot_3](https://user-images.githubusercontent.com/31403448/56680089-c5910f80-66db-11e9-987d-2a5f66a4b7f3.jpg)


but if set area = "Admin" . No need to use EditorTemplates (Download) in plugin

**Comment by muratcakir** [comment]
This was already fixed in august 2018: [see commit](https://github.com/smartstore/SmartStoreNET/commit/1364f2d4a6eabb6778e51759e5c84267d22b6e38)

**Comment by pineportal** [comment]
thank
