### ISSUE TITLE
Mobile layout lost categoryid for OffCanvasMenuCategories

### ISSUE THREAD

**Issue by xdssoftcode** [smartstore/SmartStoreNET#1622]
The parameters dictionary contains a null entry for parameter 'categoryId' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.ActionResult OffCanvasMenuCategories(Int32, Int32, Int32)

**Comment by mgesing** [comment]
This has been fixed by a6aa3e3cd8fdb6fe23f8ed672d4f428e55c0cd3d.

**Comment by xdssoftcode** [comment]
Yes
