### ISSUE TITLE
admin Currency expression

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1637]
when use Domain Endings  ver 3.1.5

` System.InvalidOperationException: The parameter 'expression' must evaluate to an IEnumerable when multiple selection is allowed.    at System.Web.Mvc.Html.SelectExtensions.GetSelectListWithDefaultValue(IEnumerable`1 selectList, Object defaultValue, Boolean allowMultiple)    at System.Web.Mvc.Html.SelectExtensions.SelectInternal(HtmlHelper htmlHelper, ModelMetadata metadata, String optionLabel, String name, IEnumerable`1 selectList, Boolean allowMultiple, IDictionary`2 htmlAttributes)    at System.Web.Mvc.Html.SelectExtensions.ListBoxFor[TModel,TProperty](HtmlHelper`1 htmlHelper, Expression`1 expression, IEnumerable`1 selectList, IDictionary`2 htmlAttributes)    at ASP._Page_Administration_Views_Currency__CreateOrUpdate_cshtml.<TabInfo>b__0_0(TextWriter __razor_helper_writer) in C:\inetpub\vhost\ghafasekaraj.com\httpdocs\Administration\Views\Currency\_CreateOrUpdate.cshtml:line 124    at System.Web.WebPages.HelperResult.ToString()    at SmartStore.Web.Framework.UI.TabStripRenderer.RenderItemContent(HtmlTextWriter writer, Tab item, Int32 index)    at SmartStore.Web.Framework.UI.TabStripRenderer.RenderTabContent(HtmlTextWriter writer)    at SmartStore.Web.Framework.UI.TabStripRenderer.WriteHtmlCore(HtmlTextWriter writer)    at SmartStore.Web.Framework.UI.ComponentRenderer`1.ToHtmlString()    at System.Web.WebPages.WebPageBase.Write(Object value)    at ASP._Page_Administration_Views_Currency__CreateOrUpdate_cshtml.Execute() in C:\inetpub\**********\Administration\Views\Currency\_CreateOrUpdate.cshtml:line 20    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)    at System.Web.Mvc.Html.RenderPartialExtensions.RenderPartial(HtmlHelper htmlHelper, String partialViewName, Object model)    at ASP._Page_Administration_Views_Currency_Edit_cshtml.Execute() in C:\inetpub********\Administration\Views\Currency\Edit.cshtml:line 27    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()    at System.Web.WebPages.StartPage.ExecutePageHierarchy()    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)    at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
`

**Comment by Michael-Herzog** [comment]
I can't reproduce this with the current code. So it seems to be fixed.

**Comment by pineportal** [comment]
test in local  is ok.
But after the release of this error is returned.
I'm looking for a bug. And I'll put it there
