### ISSUE TITLE
More granular and hierarchical permission/ACL system

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1656]

**Comment by muratcakir** [comment]
Express single permissions with dot notation: 

**admin.catalog.product.read**
Current role can access the product manager in the backend

**admin.catalog.product.edit**
Current role can create or update products in the backend

**admin.catalog.product.delete**
Current role can delete products in the backend

**admin.catalog.product**
Can read and manage products

**admin.catalog**
Can read and manage products, categories, manufacturers, variants etc.

**admin**
Can do just anything in the backend

**public**
Can do just anything in the frontend

[...]

A permission can be **allowed** or **denied**.

* **admin.catalog** (allow)
    * **admin.catalog.variant** (deny)

Means: Grant access to all catalog except the variant module.

**UI**
The permissions should be visualized as a tree. Each node contains 3 radio buttons: **Allow, Deny, Inherit**. The latter actually means _null_.

**Comment by mgesing** [comment]
Related to #756 Make permissions suitable for multi-stores.

**Comment by mgesing** [comment]
Resolved.
