### ISSUE TITLE
Amazon Pay - Strong Customer Authentication (SCA) Upgrade

### ISSUE THREAD

**Issue by sh0xy** [smartstore/SmartStoreNET#1674]
Does the payment option already have the "SCA upgrade"?

I recently got a mail of Amazon that I should upgrade my amazon pay code to make it compatible with the upcoming PSD2-/SCA until September 14, 2019.

Amzn Link:
https://developer.amazon.com/de/docs/eu/amazon-pay-onetime/sca-upgrade.html?ld=APDELPADirect

**Comment by mgesing** [comment]
Yes, it is integrated in current 3.x branch, so it will be officially released with the next version 3.2.2.
It's not available for 3.2.1 or lower due to necessary core changes in checkout.
