### ISSUE TITLE
German Spelling: Payments.DirectDebit

### ISSUE THREAD

**Issue by sh0xy** [smartstore/SmartStoreNET#1680]
"abgeschloßen" I think it should be "abgeschlossen".

![grafik](https://user-images.githubusercontent.com/53441989/62938022-71b34f00-bdce-11e9-9f23-106679203191.png)

**Comment by sh0xy** [comment]
+ is it normal that the plugin shows these selection texts of "IBAN yes" and "IBAN no"?
Do I have to do a plugin reinstall?

**Comment by mgesing** [comment]
No, execute Plugins > Manage plugins > Edit (upper right corner) > Update language resources of all plugins.

**Comment by sh0xy** [comment]
Updating the language resources of all plugins didn't solve the issue somehow.
It still shows the two code lines.
Reinstalling didn't help either.

![iban](https://user-images.githubusercontent.com/53441989/63442284-1f5bd900-c433-11e9-8eab-eba0c4c28f58.JPG)

**Comment by Michael-Herzog** [comment]
Did you clear the cache after the resources were imported?

**Comment by mgesing** [comment]
As another solution, you can add and edit missing ressources as described [here](http://docs.smartstore.com/display/SMNET32/Managing+Languages#ManagingLanguages-HowtoAddorEditaSingleResource).

**Comment by sh0xy** [comment]
Yes I cleared the cache, but it seems to be the spelling of the resource name.

![dd](https://user-images.githubusercontent.com/53441989/63525337-d1f86e00-c4fd-11e9-8ff2-cc1bb6e6fac1.JPG)

You see, the shown name slightly differs from the name of the resource.

If I change the resource to **ipaymentdirectdebit** then it works properly (like on the picture).

Do you know why it shows **ipayment** ?
