### ISSUE TITLE
MegaSearch does not search associated products within a grouped product

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1693]
When searching for the product number or manufacturer part number of a product that is set to not be shown individually, but is associated to a visible grouped product, it will not return the grouped product as a valid search result.

**Comment by altmoola** [comment]
Could you point me in the general direction within the code to perform this change so that I can at least amend it on my site until 4.0 is released?

**Comment by altmoola** [comment]
I use the MegaSearch plugin

**Comment by Michael-Herzog** [comment]
Please contact our support regarding this issue.

**Comment by mgesing** [comment]
Resolved.
