### ISSUE TITLE
Admin customer address list ignores some properties in the address format

### ISSUE THREAD

**Issue by Sherif-Ahmed** [smartstore/SmartStoreNET#1698]
https://github.com/smartstore/SmartStoreNET/blob/8e88304151e8d917dc51c250455f1b3ec8b82bfd/src/Presentation/SmartStore.Web/Administration/Controllers/CustomerController.cs#L1151

I'm asking if this should be left to the country address format or not?
because you ignore some properties like FirstName, LastName.

**Comment by mgesing** [comment]
It's for the addresses grid on Customer edit > Address tab. First and last name are displayed in different columns.

**Comment by Sherif-Ahmed** [comment]
I think you should find another way in diplaying the addresses different than the grid or just bind the whole address with its format even if there are some other columns displaying the same data..
