### ISSUE TITLE
Solution fails to install DB if taken for the first time.

### ISSUE THREAD

**Issue by beingaddicted** [smartstore/SmartStoreNET#1702]
I am facing the following issue when trying to install the portal in DB.
Can someone please guide me how to resolve this.

Setup failed: Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.

**Comment by mgesing** [comment]
Resolved by 18bc276d56a28f72404b710318eb3a6cb860be56.
