### ISSUE TITLE
Categories should be able to be hidden from MegaMenu

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1706]
None of the following work to hide a category from the mega menu tab:

- is active flag
- setting max items per column/category to 0
- setting min child threshold to arbitrarily high number (99999)

**Comment by altmoola** [comment]
If I modify the `ShouldRender` method from the `MegaMenu.cshtml` view to just return false on certain entity ids, then it works, but it doesn't seem to be using the individual node's `MegaMenuDropdownModel` settings properly and only applies the root node's settings.

    private bool ShouldRender(TreeNode<MenuItem> node, MegaMenuDropdownModel dropdownModel)
    {
        if (!node.Value.Visible)
        {
            return false;
        }

        switch (node.Value.EntityId)
        {
            case 69:
                return false;
            case 74:
                return false;
        }

        ...

**Comment by Michael-Herzog** [comment]
I think the setting to exclude a category from the navigation tree should be available in the core domain object _category_. 

PS: the MegaMenuDropdownModel will only be prepared for categories of the highest level.

**Comment by Michael-Herzog** [comment]
Will work in 4.1.0
