### ISSUE TITLE
Mobile menu scrolling is interrupted when any slight movement in the direction of the menu's collapse occurs

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1710]
This one is a little bit harder to describe.

The off canvas menus are hard to scroll due to an issue where any slight movement of the finger in the direction of the collapse will override the scroll and attempt to collapse the menu. This occurs on all of the off canvas menus: menu, cart, wishlist, compare, etc. Because this is harder to explain I've created a gif to show the issue. The gif is a camera recording of the screen so that you can see the finger attempt to scroll. The last scroll is successful because the angle of scroll is slightly towards the right. For myself, when navigating a SmartStore style site on my phone I hold my phone in my left hand and navigate the menu with my left thumb. Because of this, there is almost always a slight left angle to my scrolling which always causes the scroll to interrupt and start collapsing the menu.

I would suggest that it is changed so that even if the menu starts to collapse, the scroll still occurs. I would like to implement this change for my site for and any suggestions on where to start looking in the code to change this would be much appreciated.

![SmartStore Menu Scroll Issue 1](https://user-images.githubusercontent.com/15036268/66335700-c7046c00-e8f8-11e9-9cc3-14400b8f0748.gif)

**Comment by muratcakir** [comment]
https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web/Scripts/smartstore.offcanvas.js#L83

https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web/Scripts/smartstore.offcanvas.js#L83

**Comment by altmoola** [comment]
https://github.com/smartstore/SmartStoreNET/blob/c6910c664528d700f8c90bf008c5de1a2df96a9f/src/Presentation/SmartStore.Web/Scripts/smartstore.offcanvas.js#L119-L122

This behaviour is clearly intentional (as apparent by the referenced code), however, commenting out this `e.preventDefault();` line makes the menu much easier to scroll.
