### ISSUE TITLE
Direct links to variations on a product

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1714]
There should exist a mechanism to have hard links to a product attribute / variation, i.e.

https://www.smartstore.com/product/product1?v=12081

**Comment by mgesing** [comment]
Such a mechanism already exists. See product edit page > tab "Attributes" > Attribute combinations > Column "Product". The link contains a query string that selects the particular variant.

**Comment by altmoola** [comment]
I see that mechanism, but when changing the attribute selection from the product page, it should change the address bar so that someone could feasibly pick a combination and copy the link to it. Only way I see to get that link as a customer is to add it to the cart and copy the link from the cart.
