### ISSUE TITLE
Price facet filter bypasses Call for Pricing and shows the approximate price of a product

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1716]
Price facet filter should hide the price specified on the product if the call for pricing flag is enabled. In the below image you can see that there are three products (images redacted) that are call for pricing but a price is shown in the facet filter.

A second note about this, I don't think the price facet filter should show up to $5 for call for pricing items, it should probably show "Call for Pricing (3)"

![image](https://user-images.githubusercontent.com/15036268/66449154-49804f00-ea11-11e9-8c98-af5665adf352.png)

**Comment by mgesing** [comment]
Resolved.
