### ISSUE TITLE
Fail when buiding database

### ISSUE THREAD

**Issue by doanhai** [smartstore/SmartStoreNET#1717]
I try install SmartStore.Net, but I got this error when install: 
"Setup failed: Column names in each table must be unique. Column name 'DisplayTagsInPreview' in table 'dbo.BlogPost' is specified more than once."
Thanks you !

**Comment by Michael-Herzog** [comment]
Please make a database downgrade to MenuItemMultistore by opening the nuget package manager console and type update-database -t MenuItemMultistore. And consider working in 3.2.x as it is the latest stable release including hotfixes.
