### ISSUE TITLE
Invalid Recaptcha-Keys --> Admin-Login impossible

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1718]
Greetings!

**Problem**: Some shop operators have **activated **ReCaptcha** without entering access data for it** and thus locked themselves out of the shop. After that they could no longer log in to the admin area.

**Expected**: Recaptcha is only activated if Recaptcha access data are entered. Ideally _valid_ access data.

Thank you very much!

**Comment by asartheen-chaosa** [comment]
admin login to the system  manager has in empty field
