### ISSUE TITLE
Price facet filter, From To box overflows into article container on IE10

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1722]
![image](https://user-images.githubusercontent.com/15036268/66799781-c5760d80-eecf-11e9-9a5a-ad6bfddee668.png)

![image](https://user-images.githubusercontent.com/15036268/66799795-d6bf1a00-eecf-11e9-9b8c-c2440013052b.png)

**Comment by muratcakir** [comment]
No support for IE10. 

Come on, seriously :-O
