### ISSUE TITLE
Issue with Mini Cart after error 

### ISSUE THREAD

**Issue by CompleteCoders** [smartstore/SmartStoreNET#1725]
Goto: https://demo.smartstore.com/frontend/en/ladies-sports-jacket
Add 100 of the item to the cart
Go back to the link, add another 100 items.  
Result: you see error message
Click the Shopping Basket icon at the top of the page
Result: The mini carts spins non-stop and doesn't display.  Reload the screen works ok then.

**Comment by altmoola** [comment]
Confirmed for me too. Don't need to reload though, just changing to Wishlist and back worked.
