### ISSUE TITLE
Product tag count should filter also based on VisibleIndividually

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1730]
It's odd to see a product tag count of 4 when only 3 of those products are visible individually. That means you click the tag that says 4 and only 3 products appear.

**Comment by altmoola** [comment]
From `ProductTagService`:

    where (!p.LimitedToStores || storeId == sm.StoreId) && !p.Deleted && p.Published && p.VisibleIndividually

From the very lonely SP `[dbo].[ProductTagCountLoadAll]`:

	WHERE
		p.[Deleted] = 0
		AND p.Published = 1
		AND p.VisibleIndividually = 1

**Comment by mgesing** [comment]
When working with 4.x `update-database -TargetMigration Merge5` must be executed to take effect.
