### ISSUE TITLE
Forced "ab" Price Display gets fake base price exported to GMC

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1736]
Hi! **_Just for the record ..._** 

**Problem:** a shop owner likes the "**ab** XXX €" price display in product lists -- for marketing reasons. He uses a forum workaround to get that (entering a higher price than lowest combo price)
http://community.smartstore.com/index.php?/topic/48497-preis-ab/?hl=preise#entry274142

And that wrong price is then exported to his Google Mercant Center (GMC) ... and displayed in the Google advertising there.

Widget BlueBox -- Attribute combination prices for length:
100 € for 40 cm length
200 € for 66 cm length
300 € for 99 cm length
 
In the normal price field a fake "101 €" as workaround entered so that the "ab" reference is forced & then displayed in the product lists.
But: exactly that wrong price (101 €) will be exported to GMC.

**Expected:**
- no export from wrong base price to GMC if there are attribute prices
- a switch to manually force that "ab" & ideally an input field to set a price prefix 

I heard there is some work on this. Thanks!

**Comment by mgesing** [comment]
Resolved by 00b1bb5cb289413b1abe0df5b42bec329526105f. Do not misuse fields, otherwise unwanted results may occur.
