### ISSUE TITLE
Order details notes created on friendly value is wrong

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1751]
Following code is wrong, this will result in an improper relative time. This is because the `createdOn` variable is used, but it has been converted to local time, however later when formatted, the time is not converted.

    var createdOn = _dateTimeHelper.ConvertToUserTime(orderNote.CreatedOnUtc, DateTimeKind.Utc);

    model.OrderNotes.Add(new OrderDetailsModel.OrderNote
    {
        Note = orderNote.FormatOrderNoteText(),
        CreatedOn = createdOn,
        FriendlyCreatedOn = createdOn.RelativeFormat(false, "f")
    });

To fix:

    FriendlyCreatedOn = orderNote.CreatedOnUtc.RelativeFormat(false, "f")

**Comment by mgesing** [comment]
> but it has been converted to local time, however later when formatted, the time is not converted.

Because it is already converted.

> FriendlyCreatedOn = orderNote.CreatedOnUtc.RelativeFormat(false, "f")

That would lead to display of the UTC date and CreatedOn and FriendlyCreatedOn would be different. See first parameter of RelativeFormat.
