### ISSUE TITLE
Setup failed: An object named 'permissionrolemapping' already exists in the database.

### ISSUE THREAD

**Issue by LiangTian168** [smartstore/SmartStoreNET#1755]
Please help me, thank you！

**Comment by LiangTian168** [comment]
![image](https://user-images.githubusercontent.com/56328415/69031302-ba555680-0a14-11ea-94ee-bcaa50ada4b3.png)

**Comment by mgesing** [comment]
You have to execute the following statement in  the Package Manager Console:
`update-database -TargetMigration CategoryExternalLink`
