### ISSUE TITLE
IBAN should be listed on admin order printout

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1756]
**Problem**: a smartstore 3.2.2 shop operator gets an order with direct debit. He has a workflow: he processes direct debits manually. He prints the order from the order overview in the **onlineshop admin area** (not from email). The printout shows everything about the order ... except for the **payment details IBAN, BIC, account holder etc.**

**Desired**: Account details are listed on the order printout so that the shop operator can carry out the collection with them.

--
Problem: ein Shopbetreiber bekommt einen Auftrag mit Lastschrifteinzug. Er hat einen Workflow: er arbeitet Lastschriften händisch ab. Dazu druckt er sich den Auftrag aus der Auftragsübersicht im Adminbereich aus (nicht aus der Mail). In dem Ausdruck steht zwar alles zur Bestellung ... bis auf die Kontoangaben IBAN, BIC, Kontoinhaber usw.

Gewünscht: Kontoangaben werden auf dem Auftrags-Ausdruck gelistet, damit der Shopbetreiber den Einzug damit ausführen kann.

**Comment by Michael-Herzog** [comment]
Group the IBAN into number blocks of 4 for better readability (eg: DE22 8735 8881...)
