### ISSUE TITLE
Tree Permissions: various issues

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1771]
* Plenty duplicate node entries (AccessBackend, AccessShop) > Check whether migration issue
* **Plugin.Read** must be _allowed_ to enable configuration of ANY plugin. Even if a plugin has been explicitly allowed.
    * Problem: with **Plugin.Read** set to true, the Plugins menu item is visible and unfolds other _disallowed_ plugins.
* The **Configuration** menu item is visible and unfolds an empty dropdown, although it has been completely disallowed.
* **OutputCache** needs permission entries
* **MiniProfiler** needs permission entries
* **ContentSlider** needs permission entries
* **Dashboard** looks ugly if **Orders** has been disallowed

**Comment by mgesing** [comment]
Resolved.
