### ISSUE TITLE
MegaMenu Brands and ContentSlider Images do not use the CDN specified for the store

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1783]

**Comment by Michael-Herzog** [comment]
Can't be reproduced. The code for CDN is central. If one picture can be loaded over CDN all pictures can. Please provide a link to a store where this problem occurs.

**Comment by muratcakir** [comment]
The problem is the usage of the URL retrieving method. Details TBD.

**Comment by Michael-Herzog** [comment]
Seems to be fixed now
