### ISSUE TITLE
ACL support for manufacturers

### ISSUE THREAD

**Issue by adamtrip** [smartstore/SmartStoreNET#1790]

**Comment by mgesing** [comment]
This is already [implemented](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Libraries/SmartStore.Core/Security/Permissions.cs#L53) for the next version 4.0.

**Comment by adamtrip** [comment]
Maybe i miss explained what i was saying. Imagine if we have manufacturer  A, B, C and D. And i want to block customer role "Guest" to view C and D manufacturers.
