### ISSUE TITLE
Entitypicker issue when overridden in a plugin regarding the form action (url)

### ISSUE THREAD

**Issue by Sherif-Ahmed** [smartstore/SmartStoreNET#1797]
I overridden the Picker action methods (GET, POST) in a plugin to add some more filteration.
My view in the plugin contains 2 entity picker dialogs on should work as normal so I didnot add a DialogUrl and the other should point to the newly created action in my plugin.

When I load the picker ... the html is being loaded only one time ...

so when I load the normal picker and then try to click on my custom picker ... the html dialog is already loaded and the form had the url pointing to Entity/Picker on the web project ....

The issue is when loading the dialog the, it checks if the dialog is found then won't load it again ... below is the snippet for that: 

https://github.com/smartstore/SmartStoreNET/blob/649c2b0b434a57322e8f9aeab5b14e8c7b95c3a5/src/Presentation/SmartStore.Web/Scripts/smartstore.entityPicker.js#L147-L200

**Comment by mgesing** [comment]
In line 149, the dialog selector is built via opt.entityType (e.g. "product" for product picker), i.e. there can be several picker dialogs if you use a different opt.entityType for your entities.

**Comment by Sherif-Ahmed** [comment]
Yes, You are right ... Thank you
