### ISSUE TITLE
TinyImage: add option to optimize all existing pictures

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1804]
TinyImage _seems_ to work **only on newly added (or touched)** product pictures.
So for shops with **fresh** TinyImage-Install & thousands of **existing** pictures its lots of **clickwork** to have them optimized ->
A Shopowner asked for an new option to optimize all existing pictures **in one go**.

http://docs.smartstore.com/display/SDDE32/TinyImage  -- TinyImage Docs (german)
https://smartstore.com/de/produkte/premium-edition#block-895  -- TinyImage on Homepage (german)

**Comment by muratcakir** [comment]
That's easy. Just delete all cached images: **System > Maintenance > Clear image cache**. TinyImage will hook into thumbnail generation from now on.
