### ISSUE TITLE
The order list summary do not respect all list filters and shows wrong aggregate values

### ISSUE THREAD

**Issue by CNA1823** [smartstore/SmartStoreNET#1818]
When i'm using the store, and i'm in the order list(Admin/Order/List) part of the store like the picture i attach to this issue, when ever i'm using a filter for checking for example: paid orders the sum in down left part of table shows me a wrong number. how can i fix that??

[http://uupload.ir/files/v8b7_untitled.jpg](url)

**Comment by pineportal** [comment]
when use payment filter
![image](https://user-images.githubusercontent.com/31403448/77097297-d0583f80-6a25-11ea-8053-e8f773184141.png)

sum total incorrect
![image](https://user-images.githubusercontent.com/31403448/77097354-e7972d00-6a25-11ea-9ce4-d521c3dfc1a0.png)
