### ISSUE TITLE
Ghost facet filter groups will appear is a numeric value is assigned that matches to a different spec option

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1823]
Hard to describe, but when the indexer runs, if a specification attribute option is assigned to a product, and that option has a Numeric Value associated to it (let's say 10). If the indexer sees a completely different specification attribute option that also has a Numeric Value of 10 then it associates that option to the product when really it's not there.

Spec option 1 (Bath Capacity):
![Capture_060320091245AM](https://user-images.githubusercontent.com/15036268/76100845-a49b7b00-5f8a-11ea-9dfe-93f9c8e326c6.jpg)

Spec option 2 (Max Load):
![Capture_060320091844AM](https://user-images.githubusercontent.com/15036268/76101320-7a968880-5f8b-11ea-9635-266ba2480542.jpg)

Product assignment (only to spec option 1):
![Capture_060320091634AM](https://user-images.githubusercontent.com/15036268/76101154-2c818500-5f8b-11ea-9d5c-ed706e49fc63.jpg)

Resulting facet filter groups (shows option 1 and option 2):
![Capture_060320091759AM](https://user-images.githubusercontent.com/15036268/76101250-5f2b7d80-5f8b-11ea-8245-82f00dc1b9c6.jpg)

Edit 1: It also only appears to do it if (in this case) Spec option 2 has Search filter presentation set to Numeric range.

**Comment by mgesing** [comment]
Resolved. It's breaking change that requires the search index to be recreated.
