### ISSUE TITLE
New Maint' Task "remove unused pictures"

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1826]
Idea from http://community.smartstore.com/index.php?/topic/50235-überflüssige-daten-aus-mediastorage-löschen/?p=279354

It would be great if such a task would be available centrally under the maintenance area in the backend at some point:

**"remove unused pictures**" or something

Does this come with **Media Manager** for version 4?

**Comment by muratcakir** [comment]
Dupe of #333
