### ISSUE TITLE
Ability to zoom product page listing and other areas

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1827]
On mobile there is no way to zoom on anything using the standard thumb & index finger. Is this by design or is there some setting/tweaks that could enable this? I'm not sure that disabling zoom is a good UI choice for accessibility reasons. I've tried both Chrome and Firefox on mobile.

**Comment by muratcakir** [comment]
Actually there is. Just click on the image in the product page to trigger the photoswipe window. But if your image is not large enough there is nothing to zoom of course.

**Comment by altmoola** [comment]
I'm not referring to images. You can't zoom product pages, search results, listings, descriptions, etc.

**Comment by muratcakir** [comment]
Ah, ok. And yes, it is by design. And we will keep it this way. You can't pich zoom in apps or other mobile optimized sites either.
