### ISSUE TITLE
Track inventory by product attributes and Stock quantity

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1831]
I have a problem explaining its difficult.
An example of this

Zero stock inventory
![image](https://user-images.githubusercontent.com/31403448/77073693-e1dd1f80-6a04-11ea-9141-ee064896f3bb.png)

in Attributes Is Required false
![image](https://user-images.githubusercontent.com/31403448/77074298-e524db00-6a05-11ea-99f0-06e0b557c689.png)

Attribute combinations
![image](https://user-images.githubusercontent.com/31403448/77074476-274e1c80-6a06-11ea-8654-66f65f26dbfe.png)
![image](https://user-images.githubusercontent.com/31403448/77074518-359c3880-6a06-11ea-9b40-b79307f46569.png)
![image](https://user-images.githubusercontent.com/31403448/77074677-6d0ae500-6a06-11ea-8497-b10f85e8783d.png)

now active Track inventory by product attributes
![image](https://user-images.githubusercontent.com/31403448/77074753-8875f000-6a06-11ea-8ea6-25431c103cc6.png)

In some cases the buy button is disabled
![image](https://user-images.githubusercontent.com/31403448/77074904-c1ae6000-6a06-11ea-896a-fe711da961fe.png)

after select optional attributes.
![image](https://user-images.githubusercontent.com/31403448/77074976-e0acf200-6a06-11ea-8952-a87b5e17e0c7.png)

in fact this product is available but can't  order
![image](https://user-images.githubusercontent.com/31403448/77075080-0a661900-6a07-11ea-8788-f286884cea3f.png)

**Comment by mgesing** [comment]
You misunderstand attribute combinations. Please look at your screenshot with the list of attribute combinations. The combinations contain only the attribute "Color", but not the attribute "optional attribute". Therefore, they do not work if "optional attribute" is selected in the frontend.

Once all attributes are created, you have to execute "Create all combinations" and then enter the stock for each combination. In other words, the combination in backend must exactly match the selected attributes in frontend to be applied.

**Comment by pineportal** [comment]
You're right. in the inventory product We have encountered problems.
attribute combinations it's great. But we have problems  with the inventory.
I have a few ideas for inventory development.
For some, the core of store the first site needs to be updated.

***Once all attributes are created, you have to execute "Create all combinations" and then enter the stock for each combination***
The problem arises when not all combinations are stock.
I'm trying to write a inventory plugin and send it to you (and market). 
It is difficult to explain.


I think there is this problem above.
in Track inventory by product attributes check stock quantity. But it should check attributes combinations stock quantity.
![image](https://user-images.githubusercontent.com/31403448/77657088-6a723780-6f92-11ea-92f7-6f5c852cfc0a.png).

**Comment by mgesing** [comment]
You misunderstand attribute combinations. There is no attribute combination with a value for "optional attribute" in your attribute combination list. Therefore, no attribute combination stock quantity is applied if you select a value for "optional attribute" in frontend.
