### ISSUE TITLE
Images cannot be uploaded in 4.x

### ISSUE THREAD

**Issue by JanVogelsang** [smartstore/SmartStoreNET#1833]
Hello Smartstore Community,
there seems to be a bug in the latest 4.x branch that causes image uploading to not work properly anymore.  
When I upload any picture (store logo, product image) in the admin area, it does not upload the pictures. It does not even show the images that are currently being used, instead a camera icon is shown instead of the real image.  
I tested this with the same database connection, etc. in 3.2.2 and it worked.  

Before uploading the picture:  
<img width="874" alt="Before" src="https://user-images.githubusercontent.com/47158055/77399650-2290bc00-6daa-11ea-8b49-e520e4834b60.png">

After uploading, before saving:  
<img width="874" alt="After_upload" src="https://user-images.githubusercontent.com/47158055/77399674-31776e80-6daa-11ea-88d7-df9fc3c1a756.png">

After saving:  
<img width="889" alt="After_save" src="https://user-images.githubusercontent.com/47158055/77399685-389e7c80-6daa-11ea-86d9-0439571ab0da.png">

Store still with old logo:  
<img width="254" alt="Logo_unchanged" src="https://user-images.githubusercontent.com/47158055/77399712-448a3e80-6daa-11ea-8aa3-673bbe80e77e.png">

I noticed there is a javascript error when trying to upload an image:  
<img width="315" alt="Javascript_error_in_promise" src="https://user-images.githubusercontent.com/47158055/77399750-57047800-6daa-11ea-90cd-2e9614a90738.png">

**Comment by muratcakir** [comment]
Please be patient, the V4 MediaManager is still work in progress. We cannot guarantee that media related stuff will work during development.
