### ISSUE TITLE
MegaSearch: Support exact value match for numeric range filters

### ISSUE THREAD

**Issue by mgesing** [smartstore/SmartStoreNET#1839]

**Comment by stefanmuellerdo** [comment]
That is a **very nice, important search feature** and there are many applications B2C, B2B for that, eg. search for trailers with a apecific maximum load. (Anhänger mit Höchstgewicht -- "Anhänger 400 kg"  ... "Anhänger 200 - 1000 kg") --> does that work now?

**Comment by mgesing** [comment]
Yes. Note, it's a small issue that only relates to numeric range filters.
