### ISSUE TITLE
Can't update Store Image/Logo

### ISSUE THREAD

**Issue by adamtrip** [smartstore/SmartStoreNET#1843]
After updating store image nothing happens. It just stays with the smartstore default logo

**Comment by altmoola** [comment]
This could be a caching issue. Try Ctrl+F5 on your website. If that doesn't work Admin > Clear cache, then Ctrl+F5

**Comment by moslem-hady** [comment]
I have the same problem now.  when I try to upload logo, the post request to url '**/admin/media/upload?isTransient=True**' will get 500 error. because '**path**' parameter is null

**Comment by muratcakir** [comment]
New media stuff is work in progress and not stable right now.
