### ISSUE TITLE
When a product name has a forward slash in it, ignore this character when generating an image file path

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1850]
If you have a product with a name like `Product A - Type X / Type Y` then the image file path will include that slash - something like `product-a-type-x/type-y.jpg`. This may or may not be intentional I'm not sure, but it makes for very weird URLs. Would suggest preventing that character from going into the file path. If you could also point me to where this is generated in the code, I'd like to prevent it from my side.

**Comment by muratcakir** [comment]
This should not happen. Please have a look at [PictureService.GetPictureSeName()](https://github.com/smartstore/SmartStoreNET/blob/4b34b38b2db875508f5b74d489ceed6db8b85814/src/Libraries/SmartStore.Services/Media/PictureService.cs#L513). The 3rd parameter of the `GetSeName ` helper method call is `allowForwardSlash`, and its value is `false`.

Maybe `Picture.SeoFilename` was created externally?
