### ISSUE TITLE
EnumerateEntitiesAsync only ever returns Categories, thus the sitemap will only be categories

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#1851]
While investigating sitemaps I noticed that `XmlSitemapGenerator.EnumerateEntitiesAsync` only will every return Categories (assuming it's not null) which makes it so the sitemap will only ever have categories in it. Manufacturers, topics, and products will all be excluded from the sitemap.

**Comment by muratcakir** [comment]
`EnumerateEntitiesAsync` does not exist, but `EnumerateEntities`, and it should look this way: https://github.com/smartstore/SmartStoreNET/blob/4b34b38b2db875508f5b74d489ceed6db8b85814/src/Libraries/SmartStore.Services/Seo/XmlSitemapGenerator.cs#L477
