### ISSUE TITLE
Not everythin is translated

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1852]
I'm trying to translate smartstore website to my local language. I translated all the words in xml file, but when I run the page the text in the footer is not translated. It stays in english

![not-translated](https://user-images.githubusercontent.com/63068326/79052506-3f950e00-7c37-11ea-994e-ddfde3dcf907.jpg)

**Comment by mgesing** [comment]
These are not static resources. See CMS > Menus > FooterService > Menu items > Title.
Note: SmartStore provides new translations via [translate.smartstore.com](https://translate.smartstore.com/).

**Comment by dencocimbom** [comment]
Thanks for your help
