### ISSUE TITLE
Payment plugin does not work in other language

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1853]
I implemented my local language in smartstore.net site. But the payment plugins does not work. When the language is English it works fine. When I change to my local language it doesn't work. See the picture

![payment-plugin](https://user-images.githubusercontent.com/63068326/79056883-45044f80-7c5b-11ea-910d-80ec49ad36a2.jpg)

**Comment by mgesing** [comment]
Please execute: **Plugins > Manage plugins > Edit button (top right corner) > Update language resources of all plugins**. Note, string resources of plugins are located in plugin's own resources XML file (e.g. <Plugin-Systemname>/Localization/resources.en-us.xml). They are added to the database when a plugin is installed or when the above command is executed.

**Comment by dencocimbom** [comment]
Thank you
