### ISSUE TITLE
Mega menu downlaod

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1856]
The navigation bar of the project is very basic. I read that there is mega menu plugin but I can not find it. Where can I download it or buy it? I need navigation bar menu like this one in the picture 
![mega-menu](https://user-images.githubusercontent.com/63068326/79256214-e40d8f00-7e87-11ea-9e64-d151875b25b9.png)

**Comment by altmoola** [comment]
You should contact the support team for this as you'll need to buy a license.

**Comment by stefanmuellerdo** [comment]
Hi dencocimbom, Mega Menu is available in **Professional Edition** and higher. Please see https://smartstore.com/en/editions-prices   
Greetings, Stefan
