### ISSUE TITLE
Migration Seeders won't run if the migration name contains space?

### ISSUE THREAD

**Issue by Sherif-Ahmed** [smartstore/SmartStoreNET#1860]
https://github.com/smartstore/SmartStoreNET/blob/0c304a285da2db4fc0906e3d853bb8039cf09f08/src/Libraries/SmartStore.Data/Setup/MigratorUtils.cs#L82

If a migation name contains spaces, the seeders won't run ... I traced it found that this line doesnot remove the space in the name 

If you can just replace the space with an empty string will solve the issue

`return migrationId.Substring(16).Replace(" ", "");`

**Comment by muratcakir** [comment]
Why would anyone put a space in the migration name, which is actually the class name ;-) ?

**Comment by Sherif-Ahmed** [comment]
I Added a migration from the package manager console like that:
`add-migration 'Add AttributeXml And AttributeDescription Fields'`

![image](https://user-images.githubusercontent.com/6043905/80105992-f2dbfc00-8581-11ea-81b3-df58b9a956aa.png)

visual studio will automaticly create a migration file as the picture, but the class name will be 
`AddAttributeXmlAndAttributeDescriptionFields`

when the system tries to create a migration instance as of 
`CreateMigrationInstanceByMigrationId` method
```

private const string _migrationTypeFormat = "{0}.{1}, {2}";
public static DbMigration CreateMigrationInstanceByMigrationId(string migrationId, DbMigrationsConfiguration config)
{
	string migrationTypeName =
		string.Format(_migrationTypeFormat,
					config.MigrationsNamespace,
					GetMigrationClassName(migrationId),
					config.MigrationsAssembly.FullName);

	return CreateTypeInstance<DbMigration>(migrationTypeName);
}
```

here the `GetMigrationClassName(migrationId)` will generate a spaces in the migration name if I added the migration as I did.

so the result for `CreateMigrationInstanceByMigrationId`
should be something like that
`MyNamespace.AddAttributeXmlAndAttributeDescriptionFields, AssemblyName`

but instead it generate it like below
`MyNamespace.Add AttributeXml And AttributeDescription Fields, AssemblyName`

Regards,

**Comment by muratcakir** [comment]
The method `CreateMigrationInstanceByMigrationId()` was taken from EF internals without any modification.

You have spaces in your migration name `add-migration 'Add AttributeXml And AttributeDescription Fields`. Just get rid of the spaces.
