### ISSUE TITLE
mapping custom attributes

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1872]
I'm developing web site for optical shop. I need the buyer to choose prescription details that will be saved after the purchase is made. I created partial view which is showed in product details. I need the prescription details to be saved in the database when the customer makes the order. Is there way to map the custom attributes from my custom PartialView to the product attributes? See the picture
![custom-attributes](https://user-images.githubusercontent.com/63068326/80891749-7a361780-8cc6-11ea-816c-ff4914c1f634.png)

**Comment by stefanmuellerdo** [comment]
Hi dencocimbom, please also use our **dev forum** at http://community.smartstore.com/index.php?/forum/89-customize-extend-net/
Thank you!
