### ISSUE TITLE
Feature: Content Slider thumbnails of image list

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1882]
It would be nice to have a setting that will display the content slider images like this:
![image](https://user-images.githubusercontent.com/64465421/81298411-0a80ad80-9075-11ea-8bf9-e689ee4e4e4d.png)

**Comment by stefanmuellerdo** [comment]
Hi TripleNico, we can build that slider feature for you individually. Please contact our sales team: https://smartstore.com/en/contact
Greetings, Stefan
