### ISSUE TITLE
product details: Short description support enter

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#1887]
change  \r\n to <br/>

**Comment by stefanmuellerdo** [comment]
Hi pineportal, change to what? Please be more verbose :)

**Comment by moslem-hady** [comment]
it probably is `<br/>` !!

**Comment by Michael-Herzog** [comment]
For this we would have to integrate an HTML editor which can't be done for the short description as it will be displayed in product lists and therefore should not contain any breaks.
