### ISSUE TITLE
Radio-type in Form-configurator shows no other languages

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1888]
The options from a radio-type form-element are not visable for the selected language on the page. It shows only de options filled in at the "Standard" tab and not other languages.

**Comment by stefanmuellerdo** [comment]
Hi Yorams, thank you for using Smartstore and the Plugin Form Configurator http://community.smartstore.com/index.php?/files/file/143-form-configurator/ . Please use our **Community Forum** for support questions. http://community.smartstore.com/ Use Github to report bugs & features. Thank you!

**Comment by Yorams** [comment]
Hi Stefan, thanks for you answer. I post this here because it is a bug. 

![form-engels2](https://user-images.githubusercontent.com/13483484/81535337-e8837580-9369-11ea-9795-52fc787aedf0.JPG)
As you can see, English is filled in.

![form-engels1](https://user-images.githubusercontent.com/13483484/81535329-e4efee80-9369-11ea-8865-b32902997bef.JPG)
But not shown

**Comment by Michael-Herzog** [comment]
Hi,
this was fixed in the latest version (3.2.2.3) which was just uploaded to the marketplace.
Thanks for reporting.
Regards,
Michael Herzog
