### ISSUE TITLE
unexpected buttons showed on news feed

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1899]
Why unexpected buttons showed in news feed?
![buttons](https://user-images.githubusercontent.com/63068326/82132528-ec3b5000-97e0-11ea-9810-51c846525e78.png)

**Comment by Michael-Herzog** [comment]
Seems like one migration (BlogAndNewsItemPictures) didn't run properly. Please downgrade to MenuItemMultistore vie Package Manager Console > update-database -TargetMigration MenuItemMultistore

**Comment by dencocimbom** [comment]
Where is Package Manager Console?

**Comment by dencocimbom** [comment]
I get an error:

No migrations configuration type was found in the assembly 'SmartStore.Web'. (In Visual Studio you can use the Enable-Migrations command from Package Manager Console to add a migrations configuration).


![error](https://user-images.githubusercontent.com/63068326/82764602-4efb9f80-9e10-11ea-914f-13ec601ba0a5.jpg)

**Comment by Michael-Herzog** [comment]
Hi,
the default project must be SmartStore.Data.
Regards,
MIchael
