### ISSUE TITLE
Reset password cannot find email address

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1900]
Via the WebApi it is possible to add duplicate email adresses (maybe a check, exception can be placed on that?). So it happend that i got two emailadresses in the database. I deleted one of them in the database itself because the UI and WebApi only could delete one of them. Then i created a new account via the WebApi with that email address again, i can login with it and all goes well except when i try to do a Password Recovery, it says Email not found. 

I know in essential it went wrong that i entered two the same email addresses via de WebApi, but at this point how can i fix this?

**Comment by mgesing** [comment]
You should remove customers with duplicate email addresses from the customer table or set them to Deleted. You can get duplicates by SQL

```
SELECT Id, Email FROM [dbo].[Customer]
WHERE Email IN (
	SELECT Email FROM [dbo].[Customer] GROUP BY Email HAVING COUNT(*) > 1
)
```
Deleting the duplicates would work, for example similar [this way](https://www.sqlservertutorial.net/sql-server-basics/delete-duplicates-sql-server/), but only if the records do not yet have references to other tables. It is recommended to create a database backup before such an operation.
