### ISSUE TITLE
WYSIWYG editor extend Image options

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1903]
Currently the Image settings in the WYSIWYG editor are very simple. We would like to see more settings like alignment.

**Comment by TripleNico** [comment]
Hi Murat, I can understand why you wontfix this but is there an howto that we can do by ourself? I gues the WYSIWYG is based on Summernote?

**Comment by muratcakir** [comment]
Sorry for the late response. Yes, it's Summernote. But Summernote itself has VERY poor image editing capabilities, therefore we implemented a custom image plugin: [smartstore.image.js](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web/Content/editors/summernote/plugins/smartstore.image.js).

Extend it as you wish. Make a pull request, maybe we can pull your customizations into the core.
