### ISSUE TITLE
Width and height swapped in Service.EmailAFriend template

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1904]
The width and height is swapped in the Service.EmailAFriend template. The image in the email looked warped and swapping the width and height did the trick.

This is the original:
```
<img src="{{ thumb.Src }}" alt="{{ thumb.Alt }}"
    {% if thumb.Width %}width="{{ thumb.Width }}"{% endif %}
    {% if thumb.Height %}height="{{ thumb.Height }}"{% endif %} />       			
</a>
```

And if i do this the problem is gone:
```
<img src="{{ thumb.Src }}" alt="{{ thumb.Alt }}"
    {% if thumb.Width %}height="{{ thumb.Width }}"{% endif %}
    {% if thumb.Height %}width="{{ thumb.Height }}"{% endif %} />       			
</a>
```

**Comment by Yorams** [comment]
I've found that this only applies to lengthwise images. So where the height is greater than the width.

**Comment by mgesing** [comment]
I can't reproduce that. I've checked it against several images. Does that also happen when you use the preview function? Does the database have the correct values for width and height?

**Comment by Yorams** [comment]
I Checked it, and i can reproduce it. We upload images by the API, so we do not alter de database directly. But if i take a look at the image i see this:
![Knipsel](https://user-images.githubusercontent.com/13483484/83871869-2d17ec00-a731-11ea-91d9-6efdb858fd5e.JPG)
The width and height here is swapped.

But the images on the shop itself are show the right way:
![Knipsel3](https://user-images.githubusercontent.com/13483484/83872118-a7e10700-a731-11ea-9507-b995d3a7ab94.JPG)

And in the email i see this:
![Knipsel2](https://user-images.githubusercontent.com/13483484/83872141-b3343280-a731-11ea-949e-cca3cb52e893.JPG)

So i think there is something wrong in the API upload function?

**Comment by mgesing** [comment]
I can't reproduce that either. The API writes the correct width and height into my database. The API does not do this itself but uses functions of the service project for this, i.e. it should lead to the same result as if the image was uploaded via the backend.

Image processing tries to read the size from the header of the image file. Possibly this header is not correct. Can you attach the file with the wrong size here (the uploaded original)?

**Comment by Yorams** [comment]
Hi mgesing, sorry for the late answer. Here is the link to the article of the image. https://shop.tripleaudio.nl/en/axia-quasar-mic-in/hp-out-module-25u-wide

If you click on the image you can see the fullscreen version is also warped.

**Comment by mgesing** [comment]
The file of the [original image](https://shop.tripleaudio.nl/media/image/4559/15492-1.png) seems to be damaged. Neither Photoshop nor File Explorer displays the image correctly.

![damaged](https://user-images.githubusercontent.com/8446701/85006252-2a1df200-b15a-11ea-8b24-c205fd2f38ad.png)

**Comment by Yorams** [comment]
Damn, i could not find it there. thanks for the headsup!
