### ISSUE TITLE
Form-configurator admin message template not sending

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1905]
After i updated to version 3.2.2.3 the messages from the admin message template are not send. I tried to recreate the template and recreate the whole form but nothing resolves the issue. The message from the costumer message template do send. Also the admin message does not appear in the message queue.

The fault is not in the message template itself, because if i fill in the template name in the costumer field the template works.

I hope you guys can solve this problem soon because we properly missed some emails.

**Comment by Michael-Herzog** [comment]
Can't be reproduced
