### ISSUE TITLE
Mega Search: Only find records on default language not multiple

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1910]
In our shop we have the Mega Search enabled, which works nice and fast! But we noticed that the search doesn't work in multiple languages. We have setup two languages Netherlands and English. At the product we have setup the default description in Dutch, then at the English tab the English text and under the Netherlands tab the Dutch description.

Now lets take an example, Heaphone: In dutch "hoofdtelefoon" and in English "headphone" Now when i search for "hoofdtelefoon" i find the product but when i search for "headphone" there are no records found while i know the product exists and the text is in the body. 

I tried rebuilding the index but without any luck. These are the field settings:
![image](https://user-images.githubusercontent.com/64465421/82443878-867deb00-9aa2-11ea-9927-ea8ca5d663f3.png)

**Comment by mgesing** [comment]
Could you please make a screenshot from "Configuration > Regional Settings > Languages > Installed Languages" and from the full description editor of the sample product where you tried "Heaphone".

After a rebuild of the search index, there should be a field fulldescription_l-nl-nl and fulldescription_l-en-us field (created by MegaSearchPlus) if the languages are correctly configured and at least one product has a corresponding long description value.

**Comment by TripleNico** [comment]
![image](https://user-images.githubusercontent.com/64465421/82458502-07df7880-9ab7-11ea-9c62-cd058cc6f57b.png)
Product EN
![image](https://user-images.githubusercontent.com/64465421/82458660-4117e880-9ab7-11ea-96a7-04ae5bd1fdb7.png)
Product NL
![image](https://user-images.githubusercontent.com/64465421/82458693-4d9c4100-9ab7-11ea-9a62-8d05215221aa.png)
The "Standard" description is exactly the same as "Dutch"

Did a complete rebuild of the search index:
![image](https://user-images.githubusercontent.com/64465421/82459032-b8e61300-9ab7-11ea-9337-5e2a41365790.png)

And still is could find it...

**Comment by mgesing** [comment]
I think the default language is wrong. When "Standard" description contains Dutch text, your default language is Dutch, not English.

Could you please set the display order of Dutch to 1, set the display order of English to 2 (Dutch becomes the default language) and rebuild the index.

At the moment MegaSearch(Plus) indexes "Standard" and Dutch text. English however is skipped because it suspects it at "Standard" due to the default language setting, with the result that Dutch is indexed twice but English is not indexed at all.

**Comment by TripleNico** [comment]
Thanks, that did the trick. A information bar at the Index wouldn't hurt ;-)
