### ISSUE TITLE
Product URL not updated when product title has changed

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1911]
Say for example the title product is "My Awesome Product" and i then save it the product url becomes ~/my-awesome-product

But now when i change the title to "My Product" the product url doesn't get updated and still is ~/my-awesome-product what is would expect is that either the URL gest updated to ~/my-product

**Comment by altmoola** [comment]
The SEO record is created only upon the first creation of the product. If you want to change it you can, just edit the product and go to the Search engines (SEO) tab. Go to Show All -> then edit the record to be whatever you want.

**Comment by TripleNico** [comment]
Thanks, got it and understand now more why it is generated only once.
