### ISSUE TITLE
"I agree to the" privacy policy is not visible

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#1912]
please see forum
http://community.smartstore.com/index.php?/topic/50337-glitch-of-the-i-agree-to-the-privacy-policy/

> In latest version there is glitch in the bottom page if you use dark color. The "I agree to the" privacy policy is not visible

**Comment by Michael-Herzog** [comment]
Has been fixed by https://github.com/smartstore/SmartStoreNET/commit/ae25a1279804488912f75e123b1ef273da8377d6
