### ISSUE TITLE
Filter products by attribute or specification attribute

### ISSUE THREAD

**Issue by dencocimbom** [smartstore/SmartStoreNET#1916]
I'm developing web site for sunglasses. I need filter option by gender. How can I implement it?

![filet](https://user-images.githubusercontent.com/63068326/82764555-ef04f900-9e0f-11ea-90d5-a25d3cb8036b.jpg)

**Comment by mgesing** [comment]
The technical details are too extensive to be explained here. But this can be realized with the [MegaSearch Plus plugin](https://smartstore.com/en/premium-edition) and specification attributes.
