### ISSUE TITLE
SmartStore.Services.Discounts.IDiscountRequirementRule Error

### ISSUE THREAD

**Issue by Akinnagbe** [smartstore/SmartStoreNET#1919]
I cloned the project, set the branch to 4.x and set SmartStore.Web as the start up project, ran it but got this error message

Could not load type 'SmartStore.Services.Discounts.IDiscountRequirementRule' from assembly 'SmartStore.Services, Version=3.2.2.0, Culture=neutral, PublicKeyToken=null'.

Line 383:			bool pluginFound = false;
 Line 384:			bool preStarterFound = !plugin.Installed; 
Line 385:			var exportedTypes = plugin.Assembly.Assembly.GetExportedTypes(); Line 386: Line 387:			foreach (var t in exportedTypes)
--

**Comment by mgesing** [comment]
That's a version conflict. IDiscountRequirementRule no longer exists in 4.0. Please clean your bin and your Plugin folder and rebuild the solution.
