### ISSUE TITLE
Hide option prizes if "Call for price" is enabled

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1920]
The prices of options are visable if "Call for price" option is enabled. I want to hide them.

![Knipsel](https://user-images.githubusercontent.com/13483484/83122712-4e932b00-a0d4-11ea-8094-a9405187b8fd.JPG)

**Comment by mgesing** [comment]
Are these price adjustments of product attributes? Why don't you just remove them for the specific product?

**Comment by Yorams** [comment]
Sometimes we want to hide price for particular reasons. Then it is a hassle to removing and adding the prices everytime we want to temporarly hide the price.
