### ISSUE TITLE
Error after logging in from account activation page.

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1924]
If you activated your account with the link from the activation email and then try to login.  The browser is trying to send you back to the page were it comes from after you logged in. But because it doesn't exists anymore, because the email is already activated, this error appears.

(Error in English is: "Unknown email address or token. Please register again.")
![dasdasd](https://user-images.githubusercontent.com/13483484/83487140-c386ac00-a4aa-11ea-94c4-988a565b9be3.png)

**Comment by mgesing** [comment]
Duplicate #1743.
