### ISSUE TITLE
Import Profiles: Image not updated because it's the same

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1929]
We use the Import Profiles to import category images. The first time all goes well but now when i change an image then it doesn't get updated. De activity log states:
```
SmartStore Information: 8 : INFORMATION: Found equal picture in data store. Skipping field. [Pos: 145, Field: ImageUrls]
```

I double checked and it is a completely different image. However it can be that the previous image was the same size and therefore Import Profiles thinks its the same? Or has the Data store become corrupted? If so how can i reset it?

Edit:
When i try to remove the image by hand then i get an exception(error page) when clicking "save". The exception taken from the log:
![image](https://user-images.githubusercontent.com/64465421/83639600-337c5b80-a5ab-11ea-9b16-1a3b3dc70519.png)

The strange thing is that the Image now is really gone:
![image](https://user-images.githubusercontent.com/64465421/83639678-50189380-a5ab-11ea-9b6e-34fe8f162799.png)

But the backend UI still think is somewhere:
![image](https://user-images.githubusercontent.com/64465421/83639722-63c3fa00-a5ab-11ea-83a9-0daf09fe6608.png)

**Comment by mgesing** [comment]
> However it can be that the previous image was the same size and therefore Import Profiles thinks its the same?

No. The importer [compares the file content](https://github.com/smartstore/SmartStoreNET/blob/3.2.x/src/Libraries/SmartStore.Services/Catalog/Importer/CategoryImporter.cs#L219) to find equal images. Debugging should give you further information, especially the exact picture entity with the equal content.

The error message is possibly a duplicate of Issue #1745.

**Comment by TripleNico** [comment]
Alright so it is really true it the files are the same, however in this current state there is nothing that i can do except i think delete the whole category and recreate it again?

**Comment by mgesing** [comment]
Clearing the cache, restarting the application etc. If this does not help, then I would recommend debugging to find the exact reason.

And you could apply this [fix](https://github.com/smartstore/SmartStoreNET/commit/83b25d4d6cafe18860ffa1e4a885023c302ed625) so that you can remove the image at least in a regular way.

**Comment by TripleNico** [comment]
I ended up with deleting the category and then recreate it since this was a faster solution for us.
