### ISSUE TITLE
Setting "Show title" at Topic doesn't work?

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#1943]
We have a Pagebuilder story assigned to a topic, therefore we want to hide the Topic Title. For this we set the "Show title" to False then the Title is still shown?

![image](https://user-images.githubusercontent.com/64465421/84032271-5afe6a00-a997-11ea-8fe6-9b058584739b.png)

**Comment by Michael-Herzog** [comment]
Hi this was a little bug on this configuration page. These settings were meant to configure widgets only. However if you switched the option "Render as HTML widget" and then switched the option "Add wrapper around content" and then switched the first option back the options for the widget were mistakenly still displayed to be configured.

**Comment by Michael-Herzog** [comment]
You can also achieve your goal by setting an html id for the page and then hide the title by CSS.
