### ISSUE TITLE
OpenTrans: Add position for shipping costs to ORDER_ITEM_LIST

### ISSUE THREAD

**Issue by Michael-Herzog** [smartstore/SmartStoreNET#1950]
must be configurable as they don't belong there by specification. But some users want shipping costs to be exported anyway.

**Comment by Michael-Herzog** [comment]
Already there as a remark node where additional infos can be placed which weren't specified. 
Option for Lexware has to be turned on.

**Comment by Michael-Herzog** [comment]
Another option for adding a position might be needed for other WaWis which won't handle the remark.

**Comment by stefanmuellerdo** [comment]
(this issue ... missing shipping costs in opentrans ... has been reported to me by an ERP publisher)
