### ISSUE TITLE
Inclusive version for small businesses (Mysql and medium trust)

### ISSUE THREAD

**Issue by fabiortsf** [smartstore/SmartStoreNET#1960]
I would like to leave an idea.

It would be interesting to create an inclusive version that allows small businesses to use it.

In countries like Brazil and India, hosting is expensive and small businesses can only use MYSQL and medium trust environment with .net framework 4.5.

Is there a possibility?

**Comment by muratcakir** [comment]
* Medium Trust is absolutely impossible
* SQL Server Express is free and powerful
