### ISSUE TITLE
PageBuilder menu not visible

### ISSUE THREAD

**Issue by WadeMascia** [smartstore/SmartStoreNET#1970]
Hello,

I can see the 'Configuration | Page Builder' menu item on the demo site, and I can see that it links to here:
   http://demo.smartstore.com/backend/Admin/Plugin/ConfigurePlugin?systemName=SmartStore.PageBuilder

However I don't have that menu item when I run the code locally.  Do I need to enable the PageBuilder somehow?

**Comment by mgesing** [comment]
You have to install the [Page Builder plugin](http://community.smartstore.com/index.php?/files/file/163-cms-page-builder/).
