### ISSUE TITLE
Feature: Hint percent on Megasearch

### ISSUE THREAD

**Issue by amahdavy** [smartstore/SmartStoreNET#1973]
Hi,

If it is possible to show % of the compatibility of search results and our search text in the search result, it will help the customer to know the product how much is similar to search keywords.

![image](https://user-images.githubusercontent.com/36988281/85678405-bedb9f00-b6c8-11ea-9ed4-9d08fd56910d.png)

BR
Abolfazl

**Comment by mgesing** [comment]
To do something like this is unfortunately not recommended. [Scores As Percentages](https://cwiki.apache.org/confluence/display/lucene/ScoresAsPercentages):

> People frequently want to compute a "Percentage" from Lucene scores to determine what is a "100% perfect" match vs a "50%" match. This is also somethings called a "normalized score"
> 
> Don't do this.
> 
> Seriously. Stop trying to think about your problem this way, it's not going to end well.
