### ISSUE TITLE
UrlRewriter only works temporarily

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1974]
For some reason the UrlRewriter plugin stopped working. I have the following rules:

```
/$ /klant [R=301, NC, H=masterclass.tripleaudio.nl]
/*/shippinginfo$ /faq#verzending-en-retour [R=301, NC, H=shop.tripleaudio.nl]
```

I run version 3.2.2 of the plugin. It is not limited to stores.

A week ago i made another rewrite:
```
/*/contact$ /contactus [R=301, NC]
```
And that one suddenly also stopped working...

**Comment by Michael-Herzog** [comment]
Should be fixed in 4.0.0
