### ISSUE TITLE
Form Configurator: Only working in one store

### ISSUE THREAD

**Issue by Yorams** [smartstore/SmartStoreNET#1975]
I tried to get an answer in the forums but no one's answering.

I get a unknown error with a form made with the Form Configurator. I don't know why this error occours. I tried to turn off some fields but that does not solve it. 

With some testing i discovered the following: We have a store for our webshop and a store for our website. Strangely enough, all forms only work in the webshop store and not in the website store.

![post-45190-0-23271900-1592465710](https://user-images.githubusercontent.com/13483484/85862029-82d83500-b7c1-11ea-862b-b91e3fcab92f.jpg)
![post-45190-0-19441100-1592488828](https://user-images.githubusercontent.com/13483484/85862034-84a1f880-b7c1-11ea-8796-b42a1ba693d4.jpg)

**Comment by Michael-Herzog** [comment]
I've corrected this in V4. In the meantime make sure there are valid URLs determined in the shop configuration.
