### ISSUE TITLE
Add MinDays and MaxDays to delivery time

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1978]
- Both nullable
- New option: Show delivery date instead of delivery time name (default: true)
- Delivery date text
    - If MinDays > 0 && MaxDays == null: _Not before [PrettyDate]_
    - If MinDays == null && MaxDays > 0: _Not later than [PrettyDate]_
    - If MinDays > 0 && MaxDays > 0: _Between [PrettyDate] and [PrettyDate]_
    - If MinDays > 0 && MaxDays > 0 && MinDays == MaxDays: _On [PrettyDate]_

**Comment by mgesing** [comment]
Resolved.
