### ISSUE TITLE
Rule Builder: install some sample rulesets

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1982]
Cart Rules:
- Buy three for the price of two
- Get 10 % discount on weekends
- Get 20 % on all [Brand] articles
- Get 20 % on all [Category] articles
- Free delivery for all orders over X amount

Product Rules
- Create a virtual (flopsellers) category with 20 % discount on all products

Customer Rules:
- ... TBD

**Comment by stefanmuellerdo** [comment]
some ideas :

Customer Rules

Select inactive customers in a customer group "Inactive customer 12-24 months" (all those who have not ordered anything for 12-24 months) 
and then in **2nd rule** send a mail with some kind of voucher. 

Select top customers in a customer group "Top customers" for later use

Select new customers 3 months after the first order, shipping costs will be free with the next order 

Offer customers who have returned something for the first time a small discount for the next order

**Comment by mgesing** [comment]
Resolved.
