### ISSUE TITLE
Add native lazy loading attributes to images

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#1990]

**Comment by muratcakir** [comment]
Resolved

**Comment by stefanmuellerdo** [comment]
Hi, does this mean there is lazy image loading in Smartstore **4.0.1?** 
Would be a nice performance feature for a bugfix relase :) 
Greetings, Stefan

**Comment by muratcakir** [comment]
Yes, below the fold images are loaded lazily by the browser now.
