### ISSUE TITLE
Import/Export error

### ISSUE THREAD

**Issue by LoraVi** [smartstore/SmartStoreNET#1993]
hi there,
we just installed the new version 4.0 and the import/export buttons in the configuration menu return [THIS](https://www.publimediadigital.it/wp-content/uploads/2020/06/Schermata-2020-06-30-alle-09.59.14.png) server error.
In the release description it was written it should have been solved. Could you please give me any suggestion how to solve this issue?
thanks

**Comment by Michael-Herzog** [comment]
Hi,
I can't repduce this problem. Was this a fresh installation or an upgrade? Are there other things which don't work as expected? 
Regards,
Michael

**Comment by LoraVi** [comment]
Hi Michael,
it is a fresh installation.
 we found out what the issue was caused by: we were using sql compact and there was the server error. We switched to sql server and it works. 
However the problem right now is that I need to export products from shops that are using sql compact and i have no idea how to do it. can you give me any suggestion please? Is there a way to switch database without loosing data?
thanks a lot for your support!
Kind regards
Lora
Publimedi@
Sede amministrativa 
via San Giorgio, 1 
34123 Trieste
Tel. +39 040 3220125
P.I. 01052270327
Numero REA  TS - 121202 del 15/10/2003
www.publimediadigital.it <http://www.publimediadigital.it/>





Questo messaggio è rivolto unicamente ai destinatari indicati e può contenere informazioni riservate o confidenziali. Chi lo ricevesse per errore è pregato di cancellarlo e di informarci immediatamente, telefonando al numero 040 3220125 o inviando un'e-mail all’indirizzo info@publimediadigital.it <mailto:info@publimediadigital.it> Ogni altro uso del presente messaggio è proibito sia ai sensi dell’art. 616 c.p. che ai sensi del Regolamento Privacy UE 2016/679 "GDPR". 
 
This message is for the designated recipients only and may contain privileged or confidential information. If you have received it by mistake, please notify the sender immediately calling +39 040 3220125 or via email info@publimediadigital.it <mailto:info@publimediadigital.it> and delete the original. Any other use of the e-mail is prohibited in pursuance Of the European Parliament And Of The Council "GDPR".
