### ISSUE TITLE
Blog editing: saving a blog post may post CreatedDate in wrong format, leading to a validation error

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#2015]

**Comment by Michael-Herzog** [comment]
Very rare problem. Only occurs if the blog post is open in edit view and the language was switched in another tab (eg. frontend or other backend tab). Switching the language on the editing view won't lead to this problem as the date will be loaded with changed format. 

All date controls behave like this. e.g. Product > Price > Special price start date
