### ISSUE TITLE
Adding new report almost same with OrderAverageReport, code debug in VS with iisexpress works fine, but update IIS site always had exception "public action method 'OrderCustomerCategoryReport' was not found on controller 'SmartStore.Admin.Controllers.OrderController'."

### ISSUE THREAD

**Issue by kevin271759395** [smartstore/SmartStoreNET#2018]
It's there any deploy special steps or notice? pls advise below issue:

Adding new report almost same with OrderAverageReport, code debug in VS with iisexpress works fine, but update IIS site always had exception "2020-07-17 05:25:32,133 [30] SmartStore.Admin.Controllers.HomeController - 执行处理程序“System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper”的子请求时出错。 [admin@tegsite.com GET http://192.168.169.100:1111/admin]
System.Web.HttpException (0x80004005): 执行处理程序“System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper”的子请求时出错。 ---> System.Web.HttpException (0x80004005): Execution of the child request failed. Please examine the InnerException for more information. ---> System.Web.HttpException (0x80004005): A public action method 'OrderCustomerCategoryReport' was not found on controller 'SmartStore.Admin.Controllers.OrderController'.
   在 System.Web.Mvc.Controller.HandleUnknownAction(String actionName)"

Index.cshtml
 @{ Html.RenderAction("OrderAverageReport", "Order"); }
 @{ Html.RenderAction("OrderCustomerCategoryReport", "Order"); }   //add new report

SmartStore.Admin.Controllers.OrderController
[NonAction]
        protected virtual IList<OrderAverageReportLineSummaryModel> GetOrderCustomerCategoryReportModel()
        {
          //... similar to existing method  "GetOrderAverageReportModel"

            return model;
        }

        [ChildActionOnly]
        public ActionResult OrderCustomerCategoryReport()
        {
            var model = GetOrderCustomerCategoryReportModel();
            return PartialView(model);
        }

        [GridAction(EnableCustomBinding = true)]
        public ActionResult OrderCustomerCategoryReportList(GridCommand command) {...}

**Comment by mgesing** [comment]
Probably the application loads an outdated assembly without the new child method. Please try out following [web.config change](http://community.smartstore.com/index.php?/topic/49179-rss-plugin/#entry274981).
