### ISSUE TITLE
Question: Keyword not supported: 'initial catalog'

### ISSUE THREAD

**Issue by nadarmuthukumar** [smartstore/SmartStoreNET#2021]
This is a question:

I have pulled the latest SmartStoreNET V4.0.0 I managed to build the solution successfully in my local machine running in Win10 using VS2017, IIS v10, DotNet Framework 4.6.1, SQL 2017

When I hit F5 to run the app in VS2017 (IIS Express), I get to the install page and there I enter the same SQL database, this works fine. 

But after successful install I get the error mentioned in the title at line 47 Source File: D:\Source Code\SmartStore\SmartStoreNET_GIT\src\Libraries\SmartStore.Data\EfRepository.cs

Although I've set up the project as a SQL server express project it is picking SQL compact.

https://user-images.githubusercontent.com/5547364/87913334-8c854d80-ca8c-11ea-9568-f54551894914.png

Any tips about what the issue could be? Here the full stack trace:
[ArgumentException: Keyword not supported: 'initial catalog'.]
   System.Data.SqlServerCe.SqlCeConnectionStringBuilder.GetIndex(String keyword) +156
   System.Data.SqlServerCe.SqlCeConnectionStringBuilder.set_Item(String keyword, Object value) +31
   System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value) +183
   System.Data.SqlServerCe.SqlCeConnectionStringBuilder..ctor(String connectionString) +168
   System.Data.SqlServerCe.SqlCeConnection.set_ConnectionString(String value) +225
   System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<SetConnectionString>b__18(DbConnection t, DbConnectionPropertyInterceptionContext`1 c) +12
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +72
   System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.SetConnectionString(DbConnection connection, DbConnectionPropertyInterceptionContext`1 interceptionContext) +360
   System.Data.Entity.Infrastructure.SqlCeConnectionFactory.CreateConnection(String nameOrConnectionString) +442
   System.Data.Entity.Internal.LazyInternalConnection.Initialize() +309
   System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName() +12
   System.Data.Entity.Internal.LazyInternalContext.get_ProviderName() +11
   System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context) +92
   System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +514
   System.Data.Entity.Internal.InternalContext.Initialize() +20
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +16
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +53
   System.Data.Entity.Internal.Linq.InternalSet`1.AsNoTracking() +18
   System.Data.Entity.Infrastructure.DbQuery`1.AsNoTracking() +46
   SmartStore.Data.EfRepository`1.get_TableUntracked() in D:\Source Code\SmartStore\SmartStoreNET_GIT\src\Libraries\SmartStore.Data\EfRepository.cs:47
   SmartStore.Services.Security.AclService.get_HasActiveAcl() in D:\Source Code\SmartStore\SmartStoreNET_GIT\src\Libraries\SmartStore.Services\Security\AclService.cs:47
   SmartStore.Web.Framework.<>c.<Load>b__2_6(IComponentContext c) in D:\Source Code\SmartStore\SmartStoreNET_GIT\src\Presentation\SmartStore.Web.Framework\DependencyRegistrar.cs:446
   Autofac.<>c__DisplayClass5_0`1.<Register>b__0(IComponentContext c, IEnumerable`1 p) +10
   Autofac.Builder.<>c__DisplayClass0_0`1.<ForDelegate>b__0(IComponentContext c, IEnumerable`1 p) +14
   Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) +43
   Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) +103

[DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = DbQuerySettings (DelegateActivator), Services = [SmartStore.Core.Data.DbQuerySettings], Lifetime = Autofac.Core.Lifetime.MatchingScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope ---> Keyword not supported: 'initial catalog'. (See inner exception for details.)]
   Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget) +253
   Autofac.Core.Resolving.<>c__DisplayClass5_0.<Execute>b__0() +18
   Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator) +206
   Autofac.Core.Resolving.InstanceLookup.Execute() +145
   Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +176
   Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +24
   Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance) +74
   Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters) +54
   Autofac.ResolutionExtensions.Resolve(IComponentContext context, IEnumerable`1 parameters) +102
   Autofac.ResolutionExtensions.Resolve(IComponentContext context) +75
   SmartStore.Web.Framework.<>c.<AttachToComponentRegistration>b__3_0(Object sender, ActivatedEventArgs`1 e) in D:\Source Code\SmartStore\SmartStoreNET_GIT\src\Presentation\SmartStore.Web.Framework\DependencyRegistrar.cs:466
   Autofac.Core.Registration.ComponentRegistration.RaiseActivated(IComponentContext context, IEnumerable`1 parameters, Object instance) +70
   Autofac.Core.Resolving.InstanceLookup.Complete() +77
   Autofac.Core.Resolving.ResolveOperation.CompleteActivations() +90
   Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters) +252
   Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters) +69
   Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters) +116
   Autofac.Features.LazyDependencies.<>c__DisplayClass5_1`1.<CreateLazyRegistration>b__1() +23
   System.Lazy`1.CreateValue() +429
   System.Lazy`1.LazyInitValue() +158
   System.Lazy`1.get_Value() +79
   Autofac.Integration.Mvc.AutofacFilterProvider.ResolveControllerScopedFilter(FilterContext filterContext, String metadataKey, Func`2 wrapperFactory) +376
   Autofac.Integration.Mvc.AutofacFilterProvider.ResolveControllerScopedFilters(FilterContext filterContext) +26
   Autofac.Integration.Mvc.AutofacFilterProvider.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +298
   System.Web.Mvc.FilterProviderCollection.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +132
   System.Web.Mvc.ControllerActionInvoker.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +37
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +193
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_0(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +27
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +494
   System.Web.Mvc.<>c.<BeginExecute>b__151_1(AsyncCallback asyncCallback, Object callbackState, Controller controller) +16
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +20
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +403
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +16
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_0(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +54
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +30
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +128
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +427
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +443
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

**Comment by mgesing** [comment]
Open App_Data\Tenants\Default\App_Data\Tenants\Default and enter the correct database connection string. Delete any compact database in that directory if it's not required. You may have to delete App_Data\EfCache too if the tenant was used with different database systems.

**Comment by nadarmuthukumar** [comment]
I've already checked the setting and it is correct as below,
AppVersion: 4.0.0.0
DataProvider: sqlserver
DataConnectionString: Data Source=DESKTOP-LUN4COH;Initial Catalog=smartstoregit;Integrated Security=False;Persist Security Info=False;User ID=sa;Password=pass;Enlist=False;Pooling=True;Min Pool Size=1;Max Pool Size=100;Connect Timeout=15;User Instance=False

Now I've also tried deleting the Efcache. Still no luck.
![image](https://user-images.githubusercontent.com/5547364/87953384-99279700-cac8-11ea-8fdb-c23aadd67870.png)

**Comment by mgesing** [comment]
Duplicate of #1316.

**Comment by mgesing** [comment]
Have you ever tried to connect to this SQL Server in a different way, for example using SQL Server Management Studio? What do you mean by "I enter the _same_ SQL database"?

**Comment by nadarmuthukumar** [comment]
I connect to the MS SQL only using SQL Server Management Studio 17.  SQL Server is running on my local PC. Installation was successfully complete and the DB is also created successfully. The error is coming when running the project, I've also tried deploying the project in my local PC IIS 7. Still no luck.

**Comment by mgesing** [comment]
Have you ever tried to start from scratch, i.e. delete the database and contents of the tenant folder and then start the installation again?

**Comment by nadarmuthukumar** [comment]
Yes, I tried that too this is my second build for which I've raised the question. The first time when I got this issue I Googled and found the link [#1316](https://github.com/smartstore/SmartStoreNET/issues/1316) I went through the link already raised for 3.x version. I again pulled the latest code and still I could not run it.

**Comment by nadarmuthukumar** [comment]
I tried deleting the database and the content inside the tenant folder still no luck. I also deleted the tenant folder itself and deleted the DB still no luck.

**Comment by nadarmuthukumar** [comment]
> Have you ever tried to start from scratch, i.e. delete the database and contents of the tenant folder and then start the installation again?

I tried deleting the database and the content inside the tenant folder still no luck. I also deleted the tenant folder itself and deleted the DB still no luck
