### ISSUE TITLE
Email sending error

### ISSUE THREAD

**Issue by LoraVi** [smartstore/SmartStoreNET#2025]
Hi there,
we're working with the 4.0.0. version but we keep on having the same problem, emails don't get send and when we test the email sending we get the following error message: 
System.ArgumentException: The specified string is not in the form required for a subject.
   at System.Net.Mail.Message.set_Subject(String value)
   at System.Net.Mail.MailMessage.set_Subject(String value)
   at SmartStore.Core.Email.DefaultEmailSender.BuildMailMessage(EmailMessage original)
   at SmartStore.Core.Email.DefaultEmailSender.SendEmail(SmtpContext context, EmailMessage message)
   at SmartStore.Admin.Controllers.EmailAccountController.SendTestEmail(EmailAccountModel model)

Any suggestions?

**Comment by mgesing** [comment]
According to [this post](https://stackoverflow.com/questions/7239733/resolving-the-specified-string-is-not-in-the-form-required-for-a-subject), there are probably line breaks in the subject of the email that need to be removed.

**Comment by LoraVi** [comment]
is there a way to check the string without uploading again the whole application? 
Publimedi@
Sede amministrativa 
via San Giorgio, 1 
34123 Trieste
Tel. +39 040 3220125
P.I. 01052270327
Numero REA  TS - 121202 del 15/10/2003
www.publimediadigital.it <http://www.publimediadigital.it/>





Questo messaggio è rivolto unicamente ai destinatari indicati e può contenere informazioni riservate o confidenziali. Chi lo ricevesse per errore è pregato di cancellarlo e di informarci immediatamente, telefonando al numero 040 3220125 o inviando un'e-mail all’indirizzo info@publimediadigital.it <mailto:info@publimediadigital.it> Ogni altro uso del presente messaggio è proibito sia ai sensi dell’art. 616 c.p. che ai sensi del Regolamento Privacy UE 2016/679 "GDPR". 
 
This message is for the designated recipients only and may contain privileged or confidential information. If you have received it by mistake, please notify the sender immediately calling +39 040 3220125 or via email info@publimediadigital.it <mailto:info@publimediadigital.it> and delete the original. Any other use of the e-mail is prohibited in pursuance Of the European Parliament And Of The Council "GDPR".

> Il giorno 24 lug 2020, alle ore 09:40, Marcus Gesing <notifications@github.com> ha scritto:
> 
> According to this post <https://stackoverflow.com/questions/7239733/resolving-the-specified-string-is-not-in-the-form-required-for-a-subject>, there are probably line breaks in the subject of the email that need to be removed.

**Comment by mgesing** [comment]
Have you checked your email subject(s) (e.g. of the message template) to see if it contains an invalid character and remove it if necessary?

**Comment by LoraVi** [comment]
Yes, we checked it. However the test email template is not editable and we didn’t edit any template anyway. Emails worked perfectly till 2 days ago. Then test email function stopped working and since then the emails sending was interrupted. After the completion of an order no email is sent, nor to the shop owner nor to the client.

**Comment by malafalx91** [comment]
Is there any news regarding this error? I just installed the whole system, but it's useless if the emails don't work.

**Comment by malafalx91** [comment]
I have analyzed the subject of the mail and I have noticed that with any language other than German and English it cannot take the contents of the file: all.smres.xml
Row: 4131 <LocaleResource Name="Admin.Configuration.EmailAccounts.TestingEmail">
		<Value>Testing email functionality.</Value>


trying with smtp google sends the mail with port 587 and not in 465
