### ISSUE TITLE
ProductShareCode does not work

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2027]

**Comment by mgesing** [comment]
I cannot reproduce it. Are there any error messages?

**Comment by pineportal** [comment]
I want to add a share button to social networks on the product details page.
But (ProductShareCode in setting) does not work.

**Comment by mgesing** [comment]
Did you set the setting **CatalogSettings.ShowShareButton** to True? Otherwise the button code is not rendered.

**Comment by pineportal** [comment]
![image](https://user-images.githubusercontent.com/31403448/88790132-eda7d200-d1ac-11ea-8645-9b263be20469.png)

button code is not rendered.

Do we have to write a plugin to use? or Added in the core?

**Comment by mgesing** [comment]
It's part of the core. You'll have to do some debugging to find out why it's not rendered.

**Comment by pineportal** [comment]
Thankful.
I found a problem

**Comment by pineportal** [comment]
![image](https://user-images.githubusercontent.com/31403448/88793856-bf2cf580-d1b2-11ea-9d72-c71de1c40074.png)
