### ISSUE TITLE
Editing robots.txt in the backend for a specific store is not saved

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2028]
When I change the robots.txt field for a specific store then upon save the entries I just added are gone. Also I search through the advanced settings I only find one settings for all stores? So is it possible to set specific robots.txt values per store?

Using SmartStore 3.2.2.2

**Comment by mgesing** [comment]
No, this is not possible because there can only be one robots.txt per installation. So you have to enter the disallows of all multi-stores into this one file\field.
