### ISSUE TITLE
Multilanguage store; fields standard and next language are the same but generates the same SEO URL with -2 appended

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2029]
Will try to explain this as good as possible:

When you setup your shop to support two languages, lets say Dutch and English where Dutch is the default language. Like this:
![image](https://user-images.githubusercontent.com/64465421/88632233-9a9e2400-d0b3-11ea-8385-029c407c6453.png)

This then results in localization tabs at products, categories, manufacturers, etc... like this:
![image](https://user-images.githubusercontent.com/64465421/88632341-be616a00-d0b3-11ea-8fe3-8008a10944a6.png)

Now what our backoffice collegues do is enter the Dutch text in the Standard **AND** Dutch tab and offcourse the English text into the English tab.

The problem lies in the Standard and Dutch tab, when set the titles and then hit save the SEO friendly URLs will be created. However because the Standard and Dutch tab share the same title you will get two friendly URLs but for the Dutch tab it has a -2 appended. This is offcourse by design because an URL cannot exist twice. 

However in my opinion the Standard and Dutch tabs are redundant, therefore making the Dutch tab unnecessary. It would be more user-friendly to just show two tabs in this situation: First Standard(with the flag of the default language of the store) and second the additional language like English. For example:
![image](https://user-images.githubusercontent.com/64465421/88633678-9d017d80-d0b5-11ea-87a1-467dff60d9fb.png)

Or am I missing the point of having a Standard tab and a Dutch tab even though the functions of those are exactly the same?

For our time being, would it be sufficient enough to only fill in the Standard and English tab?

Running on SmartStore 3.2.2.2

**Comment by mgesing** [comment]
"Standard" is needed as a fallback if the value for a certain language is missing or the merchant does not want to enter it.

> For our time being, would it be sufficient enough to only fill in the Standard and English tab?

Yes, if Dutch is always the default language for the installation (for all multi-stores).

**Comment by TripleNico** [comment]
Alright thanks for the explanations.

Would using the Standard tab for Default language without using the Dutch tab affect any SEO?

**Comment by mgesing** [comment]
No, because the application expects values in the standard language under "Standard".

**Comment by TripleNico** [comment]
Okay, for us SEO is most imported so this would be a suitable solution. Is there a way to regenerate all Seo URL for products? I know opening a product and then saving it will trigger this, but deleted the SEO urls for all product and now we have to regenerate them for the Standard and English text.

**Comment by mgesing** [comment]
No. The product import can create a new, active URL records but you have to provide a new slug otherwise it is ignored.

**Comment by TripleNico** [comment]
That's unfortunately. Would there be a way, maybe via a simple script, to "Resave" all products so that SmartStore would create the URL Records again?
I'v tried changing the LocalizedProptery Name value via the WebApi but doesn't seem to trigger the URL Record creation method.

**Comment by mgesing** [comment]
No. A script cannot trigger service code. Such administrative methods would typically be provided in a plugin and started e.g. by a scheduled task. Note that a "Resave" would not delete or update the URL Record. It would deactivate the old URL Record and create a new active URL Record.

**Comment by TripleNico** [comment]
Alright, I ended up making a crawler in C# that opens the edit page of a product and then clicks the save button. This does the trick for me.
