### ISSUE TITLE
Manufacturers bound to specific stores show up in all sitemaps

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2033]
When we setup manufacturers to be only display on say Store A then when we open the sitemap for store B, like: https://storeB.domain.com/sitemap.xml then the brands that supposed to be bound to Store A are shopping up in this sitemap. We have also set this for categories and products and that works all well.

Running on SmartStore 3.2.2.2

**Comment by mgesing** [comment]
This has been fixes by 9a9cccc4a8412374c954a54620e09e5d9cc693a6.
