### ISSUE TITLE
PageBuilder: Add Contentslider as block

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2036]
In the current PageBuilder it is not possible to add a Contentslider to a specific story. Only in a topic can a Contentslider be added, resulting an always topmost Contentslider . We would like to add an Contentslider at a specific position of a PageBuilder story.

**Comment by pineportal** [comment]
I think it is a good idea. I will add to the plugin Carousel  ver 4.

**Comment by szokka** [comment]
Implemented in version 4.1
