### ISSUE TITLE
Setup Failed: Invalid object name 'dbo.Customer_CustomerRole_Mapping'.

### ISSUE THREAD

**Issue by yashsharma45** [smartstore/SmartStoreNET#2050]
I am having issue while setting up and it gives me following Error:-

Setup Failed: Invalid object name 'dbo.Customer_CustomerRole_Mapping'.

I am Compiling Libraries and Presentation seprately creating different Solutions as i am unable to see Build/Web Folder After bat file running. Please help me out with this issue.

Thanks in Advance

**Comment by mgesing** [comment]
dbo.Customer_CustomerRole_Mapping no longer exists. The table has been replaced by a new entity CustomerRoleMapping.

**Comment by yashsharma45** [comment]
But i am using Latest version of code and still it gives me error. Please tell me where i have to change to make it work. I am confused in it and working for first time on it. Please Guide me through this

**Comment by mgesing** [comment]
You should check your own code for appropriate locations. It will not compile there and will generate an error.

**Comment by pksenu1998** [comment]
Setup failed: Invalid object name 'dbo.Customer_CustomerRole_Mapping ,   i am facing this error , pls help me how to fix this

**Comment by mgesing** [comment]
Duplicate of #2051.
