### ISSUE TITLE
Setup failed: Invalid object name 'dbo.Customer_CustomerRole_Mapping

### ISSUE THREAD

**Issue by pksenu1998** [smartstore/SmartStoreNET#2051]
I am trying to run this application, when I set up in management studio and click on install, it shows an error,
can someone pls help me to fix this
Setup failed: Invalid object name 'dbo.Customer_CustomerRole_Mapping

**Comment by yashsharma45** [comment]
Fix all Migrations in SmartStore.Data and Make Solutions run one by one. it will work

**Comment by CarstenVogelsang** [comment]
@yashsharma45 I have the same error, but I do not understand your hint. What do you mean with "Fix all Migrations in SmartStore.Data". The dbo.Customer_CustomerRole_Mapping is commented out in the migrations.

**Comment by mgesing** [comment]
Resolved by 230a10b03cfee4788c2d514def4ed990dee9437b.
