### ISSUE TITLE
WebApi: Change ProductPicture DisplayOrder

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2055]
It's seems that when I change the Picture.ProductPicture.DisplayOrder than I get a OData error back telling this is not implemented? So what would be the way to change the DisplayOrder of a ProductPicture?

Or is it possible to add it as extra Multipart data at the /api/{version}/Uploads/ProductImages endpoint?

**Comment by mgesing** [comment]
PUT|PATCH /ProductPictures(<ProductMediaFile.Id>)

> Or is it possible to add it as extra Multipart data at the /api/{version}/Uploads/ProductImages endpoint?

No. The endpoint sets the maximum display order plus 1.

**Comment by TripleNico** [comment]
Thanks!

**Comment by mgesing** [comment]
Not navigation, but entity endpoint: PUT|PATCH /ProductPictures(<ProductMediaFile.Id>). Example:
PATCH /ProductPictures(3462)
{"DisplayOrder":5}

PS: the Id 3462 is returned by GET /Products(<Product.Id>)/ProductPictures
