### ISSUE TITLE
WebApi Picture upload not always updated

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2056]
When you upload an image and shortly after update the recent uploaded image then it isn't always updated. I double checked and the image is different, I set the correct PictureId for the upload and get a OK response back. But when i open the picture URL it is still the old picture.

Are pictures compared by created date or hash compare?

Running ST 3.2.2.2

Still debugging and it looks like the behaviour of the Product Detail page behaves different than the Product Admin Page. In which case the Product Detail page show more after the right picture, after clearing the browser cache. 

FYI: Output Cashe plugin is not turned on, clearing database cache and restarting application doesn't matter.

Edit:
Thanks to the help of Abdon, it turns out that the Thumbnails work correctly when an existing image is updated via /api/{version}/Uploads/ProductImages but the original size isn't updated. This can be easily be checked by removing the ?size=600/70 from the image URL.

An ugly, but working, workarround is first deleting the product images before uploading the new ones.

**Comment by mgesing** [comment]
> FYI: Output Cashe plugin is not turned on, clearing database cache and restarting application doesn't matter.

Probably image cache clearing required (System -> Maintenance -> Clear image cache).

**Comment by TripleNico** [comment]
> Probably image cache clearing required (System -> Maintenance -> Clear image cache).

Would than mean that every time a picture is updated via de WebApi the action "Clear image cache" has to be called? (Haven't tested yet if this fixes the issue)

**Comment by TripleNico** [comment]
Any news on this topic?

**Comment by mgesing** [comment]
This looks like a browser cache problem. You can check this by updating the product image and reloading the product edit page in Chrome through **Ctrl-Shift-R**. Alternative **Ctrl-Shift-Del** to get the dialog to delete the image data of the browser cache.

Another workaround in code would by to change row 106 in \Views\Shared\Components\FileUploader.cshtml as follows
```
old: <img class="file-img" data-dz-thumbnail @Html.Attr("src", previewUrl, previewUrl.HasValue()) />
new: <img class="file-img" data-dz-thumbnail @Html.Attr("src", previewUrl + "&id=" + DateTime.UtcNow.Ticks, previewUrl.HasValue()) />
```
