### ISSUE TITLE
Page Builder: RTL issues

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2068]
![image](https://user-images.githubusercontent.com/31403448/91689325-1a1e8780-eb79-11ea-9c58-ecd51208e6cd.png)

![image](https://user-images.githubusercontent.com/31403448/91689337-26a2e000-eb79-11ea-97c3-e7cc1909f15b.png)

![image](https://user-images.githubusercontent.com/31403448/91689360-33273880-eb79-11ea-9d35-3acd26fc4c62.png)

![image](https://user-images.githubusercontent.com/31403448/91689390-476b3580-eb79-11ea-83fb-c382a7cf03b1.png)

**Comment by szokka** [comment]
63be001
