### ISSUE TITLE
Page Builder: Borders -> no way to reset "Border Width" to undefined / round corners ugly with borders

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#2080]
Greetings

Page Builder: Borders -> there is **no way to reset a "Border Width"** back to undefined. Workaround is to delete the block and start new.

**Round corners look ugly** with border width set to 1 px and more. 

![pagebuilder-400-text-box-border-width](https://user-images.githubusercontent.com/54363171/92457270-4f078b80-f1c4-11ea-85b7-e882d388e443.png)

Please see screen shot and story file attached. 

[story.zip](https://github.com/smartstore/SmartStoreNET/files/5187303/story.zip)

Thank you.

**Comment by stefanmuellerdo** [comment]
with smartstore 4.0**.0**

**Comment by muratcakir** [comment]
Cannot reproduce _"no way to reset width to undefined"_. Just erase the input.

**Comment by stefanmuellerdo** [comment]
ok, that "erase the input" or "0" did not work in my browser. I will retry!

**Comment by stefanmuellerdo** [comment]
Now  it works (erasing the border width)

![Anmerkung 2020-09-14 160547](https://user-images.githubusercontent.com/54363171/93096237-6d79f500-f6a4-11ea-9b33-e2298c92ccad.png)
