### ISSUE TITLE
ProductExtensions: Product inventory is not the same as the search Linq catalog and not  supported ProductVariantAttributeCombinations

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2083]
![image](https://user-images.githubusercontent.com/31403448/92706184-8e231180-f369-11ea-80a2-d6afe7822648.png)

But in the ProductExtensions extension mode is not supported ProductVariantAttributeCombinations

![image](https://user-images.githubusercontent.com/31403448/92706282-a1ce7800-f369-11ea-9c21-463a8a85ab3a.png)

**Comment by mgesing** [comment]
Related to e4415e5bc8a6b0907b157015b44754417f3bc9db.

**Comment by mgesing** [comment]
Different context and intended purpose, different code: LinqCatalogSearchService is for product lists without consideration of selected attributes. IsAvailableByStock is used for product details considering selected attributes (MergeWithCombination is executed before).
