### ISSUE TITLE
RTL: Dropdown menu doesn't render correctly on 4K display

### ISSUE THREAD

**Issue by SalehGladius** [smartstore/SmartStoreNET#2086]
![image](https://user-images.githubusercontent.com/8124646/93043207-5fa57f00-f666-11ea-96c3-9e991b041587.png)

**Comment by Michael-Herzog** [comment]
Which browser were you using?

**Comment by SalehGladius** [comment]
I tested in Chrome, Edge, Firefox.

**Comment by szokka** [comment]
I was able to reproduce this error in Chrome and Firefox, but only on your website Ketabamin.com, not in my development environment. To reproduce this error I had to activate the touch controls and select a menu item to display the drop down menu, apparently the dropdown container values for 'left' and 'right' do not get set correctly.

**Comment by szokka** [comment]
This may have been already fixed by 911264eff088d834336c14c099b6c43b5ae0b9d8
