### ISSUE TITLE
Social Media for brand page

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2092]

**Comment by muratcakir** [comment]
Please be more precise and specific. Your subject is extremely vague, nobody has a clue what you mean.

**Comment by pineportal** [comment]
for example
https://demo.smartstore.com/frontend/en/adidas

![image](https://user-images.githubusercontent.com/31403448/93802144-ef8f8e00-fc4f-11ea-9655-e876353fcea5.png)

When shared on social networks

![image](https://user-images.githubusercontent.com/31403448/93802331-2fef0c00-fc50-11ea-9b41-6dbfea44890f.png)
The image brand and title is not displayed .

I think it is better to add meta
```
 <meta property='sm:pagedata' content='' />
<meta property='og:site_name' content='' />
<meta property='og:type' content='' />
<meta property='og:url' content='' />
<meta property='og:site' content='' />
<meta property='og:title' content='' />
<meta property='twitter:card' content='' />
<meta property='twitter:title' content='' />
<meta property='og:description' content='' />
<meta property='twitter:description' content='' />
<meta property='twitter:image' content='' />
<meta property='og:image' content='' />
<meta property='og:image:width' content='' />
<meta property='og:image:height' content='' />
```
