### ISSUE TITLE
Path Traversal Vulnerability

### ISSUE THREAD

**Issue by eric-therond-sonarsource** [smartstore/SmartStoreNET#2112]
Hello
Thanks for maintaining this open-source project
I would like to report a path traversal vulnerability similar to:
- https://github.com/smartstore/SmartStoreNET/issues/1592
- https://github.com/smartstore/SmartStoreNET/issues/1592

In the [ImportController.Create](https://github.com/smartstore/SmartStoreNET/blob/760141838e741ce24079052dd82c0bfb7753e1be/src/Presentation/SmartStore.Web/Administration/Controllers/ImportController.cs#L385) method, the `model.TempFileName` user-controlled input is not validated and an attacker can perform a path traversal attack to [copy an arbitrary file into a new profil and delete the original file](https://github.com/smartstore/SmartStoreNET/blob/760141838e741ce24079052dd82c0bfb7753e1be/src/Presentation/SmartStore.Web/Administration/Controllers/ImportController.cs#L397).

![image](https://user-images.githubusercontent.com/56015232/95458867-17326600-0973-11eb-9ce4-4a0e9e8ec28a.png)

Eric

**Comment by eric-therond-sonarsource** [comment]
Thank you @mgesing for the quick fixes
For information, this vulnerability and the ones reported in https://github.com/smartstore/SmartStoreNET/issues/2113 have been found automatically by [SonarSource](https://www.sonarsource.com/) products. 
You can try [sonarcloud.io](https://sonarcloud.io) for instance, it's free for open-source projects.

Eric

**Comment by mgesing** [comment]
Thank you, Eric.
