### ISSUE TITLE
Media Manager: Replace Image Function

### ISSUE THREAD

**Issue by schillerenrico** [smartstore/SmartStoreNET#2120]
Switch images by upload a replace image, but keep tags, objects etc. as they are. 

And maybe a version log of this file.

**Comment by mgesing** [comment]
If an image with the same file name is found during the upload, a dialog **[Replace or skip](https://www.youtube.com/watch?v=lmmoyFt1Ox4&t=134s)** opens, through which the found image can be replaced.
