### ISSUE TITLE
Allow special title and meta tags for home page

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#213]
It may be sufficient to add an option <code>Use on homepage only</code> beneath the default META fields. This at least would solve the problem with duplicate META entries.

Though the user would be forced to always enter META description/keywords for any entity, as no fallback would exist anymore. But it's OK, this is something he should do anyway to enhance his SEO ranking.

> Migrated from CodePlex: [Issue #211](https://smartstore.codeplex.com/workitem/211) from [muratcakir](https://www.codeplex.com/site/users/view/muratcakir), on 12/10/2013 11:05:40 PM

**Comment by Michael-Herzog** [comment]
Can be handled by Dynamic Metatags Plugin:
http://community.smartstore.com/index.php?/files/file/67-dynamic-metatags/

**Comment by muratcakir** [comment]
We should really have this, regardless of Dynamic Metatags plugin.

**Comment by Michael-Herzog** [comment]
Maybe it's better to revert the current solution for this commit and implement it as follows:
Add explicit setting options for meta data for Homepage, News & Blog (these options are also missing), which, if they are set, overwrite the default settings.

**Comment by Michael-Herzog** [comment]
Consider also the contact page.
