### ISSUE TITLE
Alt  Image is null

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2137]
after update 4.0.1. Alt  Image is null. If it was empty, it should be name

**Comment by pineportal** [comment]
![image](https://user-images.githubusercontent.com/31403448/97418252-d7c9ba80-191d-11eb-96a8-0f5467921d47.png)

**Comment by szokka** [comment]
This probably has been fixed with fcaadeccf3af40b7898beaa0450fda61da8071d5 as Product gallery was generalized for a picture gallery view. Please verify, when version 4.1 is available.
