### ISSUE TITLE
VS Extension -> \Plugins Sub Path missing

### ISSUE THREAD

**Issue by ericbrunner** [smartstore/SmartStoreNET#2139]
Hi,

When creating a plugin from VS Extension the mandatory sub path \Plugins is missing.

SmartStore Plugin Template: latest from https://marketplace.visualstudio.com/items?itemName=SmartStoreAG.Smartstore 
VS2019 Community Version: 

> Microsoft Visual Studio Community 2019
> Version 16.7.7
> VisualStudio.16.Release/16.7.7+30621.155
> Microsoft .NET Framework
> Version 4.8.03752
> 
> Installed Version: Community

![image](https://user-images.githubusercontent.com/6480047/97674188-6741ab80-1a8d-11eb-9ab2-4d0d0736d764.png)

**Comment by ericbrunner** [comment]
@Michael-Herzog At least a thank you Eric for reporting such issue would be appropriate. 
When subfolder path is not added manually, the Plugin doesn't compile without error.

**Comment by Michael-Herzog** [comment]
Hi Eric,
I knew about this issue. That's why the description of the extension contains the following text.

> After choosing Smartstore Plugin Template and selecting the plugins folder of your Smartstore repository as the location of your new project a dialog appears where you can select all the basic functionallity which you will need for your plugin.
