### ISSUE TITLE
SearchLog admin view is susceptible to XSS

### ISSUE THREAD

**Issue by altmoola** [smartstore/SmartStoreNET#2148]
Search for **"><script>prompt(1)</script>** and when you go to the admin view, you will see a prompt.

**Comment by mgesing** [comment]
Resolved.

**Comment by altmoola** [comment]
Is there any way to get a compiled version with this fix for 3.2.1?

**Comment by mgesing** [comment]
No but you can correct it yourself. Update line 79 in ~\SmartStore.SearchLog\Views\SearchLog\List.cshtml
```
old: .ClientTemplate("<a href='" + searchUrl + "?q=<#= encodeURI(Term) #>' target='SearchWin'><#= Term #></a>");
new: .ClientTemplate("<a href='" + searchUrl + "?q=<#= encodeURI(Term) #>' target='SearchWin'><#= window.htmlEncode(Term) #></a>");
```

**Comment by altmoola** [comment]
Right, didn't even think of that! Thanks.
