### ISSUE TITLE
Add Upgrade-Notice for Microsoft Explorer-Users.

### ISSUE THREAD

**Issue by stefanmuellerdo** [smartstore/SmartStoreNET#2150]
Add Upgrade-Notice for Microsoft Explorer-Users.

Show that shop-customer a notice like this: "_Your browser is not supported. Please use a modern browser like Google Chrome, Firefox or Microsoft Edge."_
![problem-ie-1](https://user-images.githubusercontent.com/54363171/98659998-11022180-2345-11eb-82a9-0706ffbfc1d6.JPG)
![problem-ie-2](https://user-images.githubusercontent.com/54363171/98660004-13fd1200-2345-11eb-841d-4cc21d77559d.JPG)

**Comment by szokka** [comment]
redundant with #2149

**Comment by stefanmuellerdo** [comment]
Issue is fixed and included in the new relase Smartstore 4.1: **Now there is a nice infobox for explorer users.**
![explorer-notice smartstore_LI](https://user-images.githubusercontent.com/54363171/99235038-a09c4a00-27f5-11eb-8235-71560f4da105.jpg)
