### ISSUE TITLE
blog rss not working in a multistore

### ISSUE THREAD

**Issue by merashmita** [smartstore/SmartStoreNET#2153]
Navigate to a secondary/second store in a multistore. If we try to go to Rss , it does not work. 
Can check with the site which is [rudraksha life](https://rudraksha-life.com/blog).

![image](https://user-images.githubusercontent.com/20870793/98794857-8ea25c00-242f-11eb-87a7-3126e13b8d39.png)

**Comment by merashmita** [comment]
After clearing out the application pool it started to work.

**Comment by stefanmuellerdo** [comment]
thanks for reporting!
