### ISSUE TITLE
migration 3.2.2 in 4.0.1

### ISSUE THREAD

**Issue by pineportal** [smartstore/SmartStoreNET#2157]
after migration in MediaFile: number of records have errors.
[MediaType] is empty
[Extension] is empty
Name is null or empty And does not include extensions

**Comment by pineportal** [comment]
![Untitled](https://user-images.githubusercontent.com/31403448/99294039-bd1d9e00-2858-11eb-979a-5fd500a9db2d.jpg)

**Comment by stefanmuellerdo** [comment]
why did you closed that issue?

**Comment by pineportal** [comment]
After four failed migration, the 5th load was OK.I think no user should be online on the site at the time of the update.
I closed the domain.And I ran the site from Subadamin
