### ISSUE TITLE
A plugin cannot be uninstalled if it's the only one installed

### ISSUE THREAD

**Issue by GomeniucIvan** [smartstore/SmartStoreNET#2162]
Version: 4.x

Steps to reproduce the problem:

1. Install one plugin from plugins
2. Uninstall installed plugin

Expected: No plugin(s) to be installed

https://github.com/smartstore/SmartStoreNET/blob/e3de4bc58be16c63364d06ba17a736d0218b6a43/src/Libraries/SmartStore.Core/Plugins/PluginManager.cs#L401 remove plugin from from list

PluginFileParser.SaveInstalledPluginsFile(installedPluginSystemNames);
https://github.com/smartstore/SmartStoreNET/blob/e3de4bc58be16c63364d06ba17a736d0218b6a43/src/Libraries/SmartStore.Core/Plugins/PluginFileParser.cs#L89

 return without any changes

**Comment by mgesing** [comment]
And what exactly is the problem? Uninstalling a single plugin works as expected to me.

**Comment by GomeniucIvan** [comment]
Sorry for the confusing description. When you try to uninstall the last plugin. Here is the video with issue:
https://streamable.com/7epplq
