### ISSUE TITLE
MegaMenu: link for background image has no effect

### ISSUE THREAD

**Issue by mgesing** [smartstore/SmartStoreNET#2186]
Looks like [this CSS](https://github.com/smartstore/SmartStoreNET/blob/4.x/src/Presentation/SmartStore.Web/Themes/Flex/Content/_megamenu.scss#L269) is causing this. From [forum](http://community.smartstore.com/index.php?/topic/50505-v410-mega-menu-hintergrund-bild-link-funktioniert-in-frontend-nicht/).

**Comment by muratcakir** [comment]
But this line of CSS is really necessary for megamenus with images that exceed the container. Without this, the navbar is for instance not clickable anymore when an image exceeds the megamenu container and overlaps the navbar.

So, be very careful when fixing this.
