### ISSUE TITLE
WebApi: OData returns error on /Products?$top=120&$expand=ProductCategories

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2197]
Currently i'm preparing the update from 3.2.2 to v.4.1.1. meaning i have to update the OData client from v3 to v4. During the adjustment i bumped into a problem that `GET /odata/v1/Products?$top=120&$expand=ProductCategories` returns the error 
```
    "code":"","message":"An error has occurred.","innererror":{
      "message":"The 'ObjectContent`1' type failed to serialize the response body for content type 'application/json; charset=utf-8; odata.metadata=minimal'.","type":"System.InvalidOperationException","stacktrace":"","internalexception":{
        "message":"The specified type member 'MergedDataValues' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.","
```

Checking the OData Metadata than this should work? When i try it with a different object like `GET /odata/v1/Customers?$top=120&$expand=CustomerRoleMappings` then everything works as expected.

Am i overlooking something of is this not working in v4?

**Comment by TripleNico** [comment]
Thanks, thanks was a quick an easy fix. When will there be a new release of the plugin?

**Comment by mgesing** [comment]
I don't know. You'll probably get it faster if you compile it yourself. It's [Open Source](https://github.com/smartstore/SmartStoreNET/tree/4.x/src/Plugins/SmartStore.WebApi).

**Comment by TripleNico** [comment]
Thanks for the link! Just tried to build it but it seams that the WebApi isn't build by the ClickToBuild.cmd script. The rest of the plugins build just fine.
