### ISSUE TITLE
PayPal plus locale error.

### ISSUE THREAD

**Issue by firatoltulu** [smartstore/SmartStoreNET#2202]
Hi,

T get locale error from paypal. i check it locale code from paypal pages.  https://developer.paypal.com/docs/api/reference/locale-codes/ my value is wrong.
i want to change it on languages pages but it not free edit. may be it free text field.

Send
{
  "name": "Wizcircuit",
  "presentation": {
    "brand_name": "Wizcircuit",
    "locale_code": "EN",
    "logo_image": "https://www.wizcircuit.com/media/38/content/wiz_logo.png"
  },
  "input_fields": {
    "allow_note": false,
    "no_shipping": 0,
    "address_override": 1
  }
}
Receive
{
  "name": "VALIDATION_ERROR",
  "debug_id": "a1d753f9b4e7b",
  "message": "Invalid request - see details",
  "information_link": "https://developer.paypal.com/docs/api/payment-experience/#errors",
  "details": [
    {
      "field": "presentation.locale_code",
      "issue": "Invalid locale"
    }
  ]
}

https://github.com/smartstore/SmartStoreNET/blob/a242a8089e136ebc4d53215ca79f18199fc9ee36/src/Plugins/SmartStore.PayPal/Services/PayPalService.cs#L1017

**Comment by mgesing** [comment]
See [docu](https://developer.paypal.com/docs/api/payment-experience/v1#web-profiles) and search for "locale_code". Valid values are AU, AT, BE, BR, CA, CH, CN, DE, ES, GB, FR, IT, NL, PL, PT, RU, or US.
So "Configuration > Regional Settings > Languages > Unique SEO code" of your current language must match one of these values.
