### ISSUE TITLE
ImportProfiles not started when using key 'startImport'

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2211]
Sinces release 4.0 the ImportProfiles API endpoint has a new key called `startImport` this is a result from #1809 which is great it's added.

The documentation states:
>**startImport**: If set to true then the import is started. The requesting customer must have the permission to execute scheduled tasks.
>

Today i wanted to start using this feature but it seems the Import is not executed after upload. For example RAW upload info:
```RAW
POST http://MySite/api/v1/Uploads/ImportFiles HTTP/1.1
Pragma: no-cache
CacheControl: no-cache, no-store
Accept: application/json, text/javascript, */*
AcceptCharset: UTF-8
SmartStore-Net-Api-PublicKey: e004b6807e151eb63c0d80a5381a61c9
SmartStore-Net-Api-Date: 2021-03-03T12:52:32.9460996Z
Authorization: SmNetHmac1 c6rft0rVyPUwGiqIubTERbZIDjyIay5cEJu1RUVfCxA=
Content-Type: multipart/form-data; boundary=-----------------------------28947758029299
Host: MySite
Content-Length: 307595
Accept-Encoding: gzip, deflate

-------------------------------28947758029299
Content-Type: 
Content-Disposition: form-data; name="Id"

1
-------------------------------28947758029299
Content-Disposition: form-data; name="file"; Name="ProductDependingPriceImport"; deleteExisting="true"; startImport="true"; filename="CSV_DependingPrices.csv"
Content-Type: application/octet-stream

ID;DP_ItemGroupId;DP_CustomerGroupId;DP_LanguageId;DP_StoreId;DP_CustomerNumber;DP_Price;DP_CalculationMethod;DP_Delete
8;0;0;0;0;;57.7;Percental;False
9;0;0;0;0;;3.0;Percental;False
```

This result in a HTTP `200` and the response body is:
```JSON
[
  {
    "IsSupportedByProfile": true,
    "Name": "file",
    "FileName": "CSV_DependingPrices.csv",
    "FileExtension": ".csv",
    "MediaType": "application/octet-stream",
    "Exists": false,
    "Inserted": true,
    "ContentDisposition": [
      {
        "Name": "name",
        "Value": "\"file\""
      },
      {
        "Name": "Name",
        "Value": "\"ProductDependingPriceImport\""
      },
      {
        "Name": "deleteExisting",
        "Value": "\"true\""
      },
      {
        "Name": "startImport",
        "Value": "\"true\""
      },
      {
        "Name": "filename",
        "Value": "\"CSV_DependingPrices.csv\""
      }
    ]
  }
]
```

But if i look at the ImportProfile status in the backend the Import History doesn't list the recent upload history. The file however who is now linked is exactly the same i've uploaded. So in sort all seems to go well except the ImportProfile isn't started after upload.

I'd also checked user rights and the WebAPI user is of type Administrator and also there are no logs stating Unauthorised. And i changed the identifiers from Id to Name but same result.

This is how the Linked Scheduled Task is setup
![image](https://user-images.githubusercontent.com/64465421/109815880-6f267d80-7c30-11eb-85da-27a18f650054.png)

Although the Cron will run every 24 hours what i would expect of the `startImport` is that a import will run immediately, not depending of it's schedule. Like the same way in the back-end you click on `Run now`

Maybe i'm overlooking something?

**Comment by mgesing** [comment]
The API does not find the startImport parameter. Instead of putting it on the file part, I would attach a separate multipart for it. Example:

```
------------728c5a36c885477b9b9b2a16cbce2751
Content-Disposition: form-data; name="Id"

8
------------728c5a36c885477b9b9b2a16cbce2751
Content-Disposition: form-data; name="startImport"

true
------------728c5a36c885477b9b9b2a16cbce2751
Content-Disposition: form-data; name="my-file-1"; filename="api-import-test.csv"
Content-Type: application/octet-stream

<Binary file data here (length 103 bytes)...>
------------728c5a36c885477b9b9b2a16cbce2751--

```
Id 8 > ID of the import profile to attach the uploaded import file to.
startImport true > start the import immediately.
my-file-1 > raw CSV import data.

**Comment by TripleNico** [comment]
Thanks, that did the trick! 👍 Adding it as form-data instead of appending it to the form-data of the file itself.

Is it also possible to disable the email that is send after a Import run?

**Comment by mgesing** [comment]
No, the completion email is always sent.

**Comment by TripleNico** [comment]
Alright. Is that something that can be added to the roadmap? A conditional enum would help, like:

1. Always send email 
2. Only send an email only if an error occured
3. Never send email
