### ISSUE TITLE
Own folder in \Media isn't available anymore in 4.1.1

### ISSUE THREAD

**Issue by TripleNico** [smartstore/SmartStoreNET#2212]
In version 3.2.2 we have a sub folder in `~/Media` called `ProductFiles` which holds file corresponding with some product. For example `~/Media/ProductFiles/SomeTechnicalDrawing.dwg` or `~/Media/ProductFiles/AdditionalBrochure.pdf` We then added the hyperlink to the description of the product. This worked fine but in 4.1.1 this has changed, i guess due to the MediaManager managing things.

So the question would be where to store those files in 4.1.1 so they can be accessed again?

**Comment by muratcakir** [comment]
You have to upload all miscellaneous files to the **Files** album (the last one in the media manager), then reference them as usual, e.g.: `~/media/file/1234/subfolder/file.jpg`. 1234 = MediaFile.Id, subfolder = optional subfolder in Files album.

**Comment by TripleNico** [comment]
Thanks for your explanation. That confirms why it isn't currently working. Is there no alternative to link directly to local files? of is that blocked due to security reasons and the new MediaManager?

**Comment by muratcakir** [comment]
You CAN link to local files, but not via media manager. Just create a directory in your web root (it shouldn't be called _media_ although) and put your files there. Ensure that static files can be served (via web.config --> StaticFileModule). Link your files as `/mymediadir/myfile.png`.

**Comment by TripleNico** [comment]
Thanks, that seems to work!
