### ISSUE TITLE
User Email Deletion - Still Recognized as Used Email

### ISSUE THREAD

**Issue by SMWrk** [smartstore/SmartStoreNET#2231]
I've deleted a user and am attempting to create a new user with the email of deleted user. Error: "The specified email already exists" - when, in fact, this user no longer exists. Must this resolve on its own after the smartstore runs cleanup temporary files or delete logs, or does this issue embed deeper?

**Comment by Michael-Herzog** [comment]
This is soft deletion. Just have a look in the database and set the value for Deleted to false again.
