### ISSUE TITLE
Video Thumbnail not getting displayed on Product page and Product Picture page(admin section)

### ISSUE THREAD

**Issue by ParthaTFTUS** [smartstore/SmartStoreNET#2233]
Hi, 
I am using SmartStore 4.2.0 version. Currently, thumbnails or videos are not getting displayed when uploaded via the product picture section in admin page.  Thumbnail of the video is also not coming in Product page.
Screenshot attache
![video thumbnail issue](https://user-images.githubusercontent.com/95568784/152332213-74708580-934c-45a2-aa43-5e2d2fe0d823.PNG)
d

**Comment by muratcakir** [comment]
You need the **Media Manager**, which is part of the commercial [Premium Edition](https://smartstore.com/en/premium-edition) in order to be able to generate video thumbnails.
