### ISSUE TITLE
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by Akinnagbe** [smartstore/SmartStoreNET#2234]
I am using the latest branch, but keep getting the error below:

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

can you assist.

thanks

**Comment by muratcakir** [comment]
This sounds like a reference conflict with another assembly that also uses Microsoft.Bcl.AsyncInterfaces. Did you update any NuGet packages?

**Comment by Akinnagbe** [comment]
Yes I did, but somehow got it fixed, had to delete temp files and some other files.
