### ISSUE TITLE
Setup failed: Value cannot be null. Parameter name: stream

### ISSUE THREAD

**Issue by muratcakir** [smartstore/SmartStoreNET#368]
I just downloaded the latest version, set up my website in IIS and this is what I get during the installation when the install is trying to create my database.

Setup failed: Value cannot be null. Parameter name: stream 

I'm using IIS 8.5 
Windows 8

> Migrated from CodePlex: [Issue #366](https://smartstore.codeplex.com/workitem/366) from [muratcakir](https://www.codeplex.com/site/users/view/muratcakir), on 5/2/2014 4:19:38 PM

**Comment by sajjadalee** [comment]
Have anybody Worked on it?

**Comment by sajjadalee** [comment]
Does anybody fixed it?
