### ISSUE TITLE
suggestion about combination attributes

### ISSUE THREAD

**Issue by SalehGladius** [smartstore/SmartStoreNET#972]
i explain a sample:

we have 10 shirts in 3 Sizes: **S, M, L**
our small shirts are in 2 color: **red**, **blue**
and we have 2 **yellow** medium shirts, and 2 **green** large also,

for this product we need **Dropdown** or **RadioButton** and **Color Square** attributes!
when we select a **small** size, only shows **red** and **blue** **color squares**, 
and when we select a **medium** size, only shows **yellow** square,

**Comment by muratcakir** [comment]
Related to #995 and #996
